var allStopsBig = [ {name:"ARC", ident:"ARC", numeric:"MTD5762"},
{name:"Airport Rd. <span class=\"amp\">&amp;</span> Highcross", ident:"APTHICRS", numeric:"MTD2364"},
{name:"Anderson <span class=\"amp\">&amp;</span> Brighton", ident:"ADRSNBRTN", numeric:"MTD2556"},
{name:"Anderson <span class=\"amp\">&amp;</span> Burkwood", ident:"ADRSNBKWD", numeric:"MTD7460"},
{name:"Anderson <span class=\"amp\">&amp;</span> Colorado", ident:"ADRSNCO", numeric:"MTD5667"},
{name:"Anderson <span class=\"amp\">&amp;</span> Eliot", ident:"ADRSNELIOT", numeric:"MTD0211"},
{name:"Anderson <span class=\"amp\">&amp;</span> Evergreen Circle", ident:"ADRSNEVRGN", numeric:"MTD4232"},
{name:"Anderson <span class=\"amp\">&amp;</span> Fairlawn", ident:"ADRSNFRLN", numeric:"MTD2224"},
{name:"Anderson <span class=\"amp\">&amp;</span> Harding", ident:"ADRSNHRDG", numeric:"MTD3324"},
{name:"Anderson <span class=\"amp\">&amp;</span> Hawthorne", ident:"ADRSNHTHN", numeric:"MTD0564"},
{name:"Anderson <span class=\"amp\">&amp;</span> Michigan", ident:"ADRSNMI", numeric:"MTD2475"},
{name:"Anderson <span class=\"amp\">&amp;</span> Mumford", ident:"ADRSNMFRD", numeric:"MTD5145"},
{name:"Anderson <span class=\"amp\">&amp;</span> Silver", ident:"ADRSNSLVR", numeric:"MTD1132"},
{name:"Anderson <span class=\"amp\">&amp;</span> Sunnycrest", ident:"ADRSNSNYC", numeric:"MTD5463"},
{name:"Anthony <span class=\"amp\">&amp;</span> Mattis", ident:"ANTMATS", numeric:"MTD5742"},
{name:"Anthony at WalMart", ident:"ANTWLMRT", numeric:"MTD4623"},
{name:"Armory <span class=\"amp\">&amp;</span> Wright", ident:"ARYWRT", numeric:"MTD4145"},
{name:"Balboa <span class=\"amp\">&amp;</span> Prospect", ident:"BLBOAPSPCT", numeric:"MTD7256"},
{name:"Beech <span class=\"amp\">&amp;</span> Romine", ident:"BCHRMN", numeric:"MTD1422"},
{name:"Bentbrook <span class=\"amp\">&amp;</span> Staley", ident:"BNTBRKSTLY", numeric:"MTD1722"},
{name:"Beslin <span class=\"amp\">&amp;</span> Romine", ident:"BSLNRMN", numeric:"MTD5235"},
{name:"Big Lots", ident:"BL", numeric:"MTD2333"},
{name:"Bloomington <span class=\"amp\">&amp;</span> Prospect", ident:"BLOMPSPCT", numeric:"MTD1512"},
{name:"Boardwalk <span class=\"amp\">&amp;</span> Meijer", ident:"BRDWLKMJR", numeric:"MTD2212"},
{name:"Bradley <span class=\"amp\">&amp;</span> Champaign St.", ident:"BRADCMI", numeric:"MTD3123"},
{name:"Bradley <span class=\"amp\">&amp;</span> Duncan", ident:"BRADDNCN", numeric:"MTD2234"},
{name:"Bradley <span class=\"amp\">&amp;</span> Mattis", ident:"BRADMATS", numeric:"MTD3675"},
{name:"Bradley <span class=\"amp\">&amp;</span> Prospect", ident:"BRADPSPCT", numeric:"MTD3451"},
{name:"Bradley <span class=\"amp\">&amp;</span> State", ident:"BRADSTE", numeric:"MTD3254"},
{name:"Bradley <span class=\"amp\">&amp;</span> Thompson Park", ident:"TMPSNPK", numeric:"MTD2527"},
{name:"Bradley <span class=\"amp\">&amp;</span> Walnut", ident:"BRADWLNT", numeric:"MTD1051"},
{name:"Bradley at Heritage Park", ident:"HRTGPK", numeric:"MTD4625"},
{name:"Brady at Grace Baptist Church", ident:"BRDYGBC", numeric:"MTD1101"},
{name:"Broadmoor <span class=\"amp\">&amp;</span> Crescent", ident:"BDMRCRSNT", numeric:"MTD7365"},
{name:"Broadmoor <span class=\"amp\">&amp;</span> Lincoln Pl.", ident:"BDMRLCNPL", numeric:"MTD0323"},
{name:"Broadway <span class=\"amp\">&amp;</span> Bailey", ident:"BDWYBLY", numeric:"MTD1337"},
{name:"Broadway <span class=\"amp\">&amp;</span> Chapin", ident:"BDWYCHPN", numeric:"MTD5735"},
{name:"Broadway <span class=\"amp\">&amp;</span> Country Club", ident:"BDWYCCR", numeric:"MTD6222"},
{name:"Broadway <span class=\"amp\">&amp;</span> Crystal Lake Dr.", ident:"BDWYCLD", numeric:"MTD6615"},
{name:"Broadway <span class=\"amp\">&amp;</span> Elm", ident:"BDWYELM", numeric:"MTD2532"},
{name:"Broadway <span class=\"amp\">&amp;</span> Franklin", ident:"BDWYFRKLN", numeric:"MTD6141"},
{name:"Broadway <span class=\"amp\">&amp;</span> Kerr", ident:"BDWYKER", numeric:"MTD2651"},
{name:"Broadway <span class=\"amp\">&amp;</span> Lake Side Terrace", ident:"BDWYLST", numeric:"MTD2352"},
{name:"Broadway <span class=\"amp\">&amp;</span> Oakland", ident:"BDWYOKLN", numeric:"MTD5414"},
{name:"Broadway <span class=\"amp\">&amp;</span> Park", ident:"BDWYPK", numeric:"MTD3172"},
{name:"Broadway <span class=\"amp\">&amp;</span> Thompson", ident:"BDWYTPSN", numeric:"MTD1324"},
{name:"Broadway <span class=\"amp\">&amp;</span> University", ident:"BDWYUNI", numeric:"MTD2021"},
{name:"Broadway <span class=\"amp\">&amp;</span> Water", ident:"BDWYWTR", numeric:"MTD7562"},
{name:"Broadway at Save A Lot", ident:"BDWYCM", numeric:"MTD3432"},
{name:"Brownfield <span class=\"amp\">&amp;</span> Airport Rd.", ident:"BNFLDAPT", numeric:"MTD5066"},
{name:"Burwash at Windsor of Savoy", ident:"WIND", numeric:"MTD1461"},
{name:"California <span class=\"amp\">&amp;</span> Gregory Pl.", ident:"CAGRGPL", numeric:"MTD0644"},
{name:"Champaign County Courthouse", ident:"CCCH", numeric:"MTD3212"},
{name:"Champaign House", ident:"CMIHS", numeric:"MTD4027"},
{name:"Champaign Walmart", ident:"WALMART", numeric:"MTD1374"},
{name:"Chester <span class=\"amp\">&amp;</span> Water", ident:"CHSTRWTR", numeric:"MTD1234"},
{name:"Church <span class=\"amp\">&amp;</span> Carson", ident:"CHCHCRSN", numeric:"MTD2335"},
{name:"Church <span class=\"amp\">&amp;</span> Draper", ident:"CHCHDRPR", numeric:"MTD7566"},
{name:"Church <span class=\"amp\">&amp;</span> Edwin", ident:"CHCHEDWN", numeric:"MTD6503"},
{name:"Church <span class=\"amp\">&amp;</span> Elm", ident:"CHCHELM", numeric:"MTD2164"},
{name:"Church <span class=\"amp\">&amp;</span> Fair", ident:"CHCHFAIR", numeric:"MTD1427"},
{name:"Church <span class=\"amp\">&amp;</span> Garfield", ident:"CHCHGRFLD", numeric:"MTD5721"},
{name:"Church <span class=\"amp\">&amp;</span> James", ident:"CHCHJAS", numeric:"MTD4236"},
{name:"Church <span class=\"amp\">&amp;</span> Lynn", ident:"CHCHLYN", numeric:"MTD6257"},
{name:"Church <span class=\"amp\">&amp;</span> Mattis", ident:"CHCHMATS", numeric:"MTD6512"},
{name:"Church <span class=\"amp\">&amp;</span> McKinley", ident:"CHCHMCNLY", numeric:"MTD1356"},
{name:"Church <span class=\"amp\">&amp;</span> Miller", ident:"CHCHMLR", numeric:"MTD2163"},
{name:"Church <span class=\"amp\">&amp;</span> Neil", ident:"CHCHNEIL", numeric:"MTD7533"},
{name:"Church <span class=\"amp\">&amp;</span> New", ident:"CHCHNEW", numeric:"MTD5172"},
{name:"Church <span class=\"amp\">&amp;</span> Prairie", ident:"CHCHPRRE", numeric:"MTD1651"},
{name:"Church <span class=\"amp\">&amp;</span> Prospect", ident:"CHCHPSPCT", numeric:"MTD0223"},
{name:"Church <span class=\"amp\">&amp;</span> Randolph", ident:"CHCHRNDLF", numeric:"MTD2560"},
{name:"Church <span class=\"amp\">&amp;</span> Russell", ident:"CHCHRSL", numeric:"MTD5535"},
{name:"Church <span class=\"amp\">&amp;</span> State", ident:"CHCHSTE", numeric:"MTD6432"},
{name:"Church <span class=\"amp\">&amp;</span> Victor", ident:"CHCHVCTR", numeric:"MTD3244"},
{name:"Church <span class=\"amp\">&amp;</span> Willis", ident:"CHCHWLS", numeric:"MTD7654"},
{name:"Church between New <span class=\"amp\">&amp;</span> Prospect", ident:"CHCH", numeric:"MTD7155"},
{name:"Colbert Park", ident:"CBRTPK", numeric:"MTD5400"},
{name:"Coler <span class=\"amp\">&amp;</span> Church", ident:"CLRCHCH", numeric:"MTD5155"},
{name:"Coler <span class=\"amp\">&amp;</span> Fairview", ident:"CLRFRVW", numeric:"MTD3715"},
{name:"Coler <span class=\"amp\">&amp;</span> Park", ident:"CLRPK", numeric:"MTD4521"},
{name:"College Ct. <span class=\"amp\">&amp;</span> Virginia", ident:"CCVA", numeric:"MTD3163"},
{name:"Columbia <span class=\"amp\">&amp;</span> Neil", ident:"CLMBANEIL", numeric:"MTD2635"},
{name:"Cotage Grove <span class=\"amp\">&amp;</span> California", ident:"CTGRVCA", numeric:"MTD6324"},
{name:"Cottage Grove <span class=\"amp\">&amp;</span> Brighton", ident:"CTGRVBRITN", numeric:"MTD6543"},
{name:"Cottage Grove <span class=\"amp\">&amp;</span> Burkwood", ident:"CTGRVBKWD", numeric:"MTD1174"},
{name:"Cottage Grove <span class=\"amp\">&amp;</span> Colorado", ident:"CTGRVCO", numeric:"MTD4223"},
{name:"Cottage Grove <span class=\"amp\">&amp;</span> Crestwood", ident:"CTGRVCRWD", numeric:"MTD6272"},
{name:"Cottage Grove <span class=\"amp\">&amp;</span> Delaware", ident:"CTGRVDE", numeric:"MTD0206"},
{name:"Cottage Grove <span class=\"amp\">&amp;</span> Eastern", ident:"CTGRVERN", numeric:"MTD3622"},
{name:"Cottage Grove <span class=\"amp\">&amp;</span> Glenwood Oaks", ident:"CTGRVGNWD", numeric:"MTD6151"},
{name:"Cottage Grove <span class=\"amp\">&amp;</span> Green", ident:"CTGRVGRN", numeric:"MTD5363"},
{name:"Cottage Grove <span class=\"amp\">&amp;</span> Harding", ident:"CTGRVHRDG", numeric:"MTD0547"},
{name:"Cottage Grove <span class=\"amp\">&amp;</span> Illinois", ident:"CTGRVIL", numeric:"MTD4244"},
{name:"Cottage Grove <span class=\"amp\">&amp;</span> Mitchem", ident:"CTGRVMCHM", numeric:"MTD5205"},
{name:"Cottage Grove <span class=\"amp\">&amp;</span> Oregon", ident:"CTGRVOR", numeric:"MTD2321"},
{name:"Cottage Grove <span class=\"amp\">&amp;</span> Pennsylvania", ident:"CTGRVPA", numeric:"MTD4365"},
{name:"Cottage Grove <span class=\"amp\">&amp;</span> Philo", ident:"CTGRVPHILO", numeric:"MTD1262"},
{name:"Cottage Grove <span class=\"amp\">&amp;</span> Sunnycrest", ident:"CTGRVSYNC", numeric:"MTD3623"},
{name:"Cottage Grove <span class=\"amp\">&amp;</span> Washington", ident:"CTGRVWASH", numeric:"MTD1636"},
{name:"Country Fair Dr. <span class=\"amp\">&amp;</span> Church", ident:"CFDCHCH", numeric:"MTD3642"},
{name:"Country Fair Dr. <span class=\"amp\">&amp;</span> Park", ident:"CFDPK", numeric:"MTD3416"},
{name:"Country Fair Dr. <span class=\"amp\">&amp;</span> University", ident:"CFDUNI", numeric:"MTD4555"},
{name:"Crescent <span class=\"amp\">&amp;</span> Greendale", ident:"CRSNTGRNDL", numeric:"MTD1162"},
{name:"Crescent <span class=\"amp\">&amp;</span> John", ident:"CRSNTJOHN", numeric:"MTD1752"},
{name:"Crescent <span class=\"amp\">&amp;</span> Lawndale", ident:"CRSNTLWNDL", numeric:"MTD5565"},
{name:"Crescent <span class=\"amp\">&amp;</span> Ola", ident:"CRSNTOLA", numeric:"MTD3422"},
{name:"Crescent <span class=\"amp\">&amp;</span> Parkdale", ident:"CRSNTPKDL", numeric:"MTD2355"},
{name:"Crescent <span class=\"amp\">&amp;</span> Rodney", ident:"CRSNTROD", numeric:"MTD0241"},
{name:"Crescent <span class=\"amp\">&amp;</span> Round Barn Manor", ident:"CRSNTRBM", numeric:"MTD3412"},
{name:"Crescent <span class=\"amp\">&amp;</span> Round Barn Road", ident:"CRSNTRBR", numeric:"MTD0513"},
{name:"Crescent <span class=\"amp\">&amp;</span> Sangamon", ident:"CRSNTSANG", numeric:"MTD4557"},
{name:"Crescent <span class=\"amp\">&amp;</span> Southwood", ident:"CRSNTSWD", numeric:"MTD5221"},
{name:"Crescent <span class=\"amp\">&amp;</span> William", ident:"CRSNTWLM", numeric:"MTD5451"},
{name:"Crescent at Jefferson Middle School", ident:"CRSNTJMS", numeric:"MTD4272"},
{name:"Cunningham <span class=\"amp\">&amp;</span> Oakland", ident:"CNHMOKLN", numeric:"MTD6674"},
{name:"Cunningham <span class=\"amp\">&amp;</span> Park", ident:"CNHMPK", numeric:"MTD6416"},
{name:"Cunningham <span class=\"amp\">&amp;</span> University", ident:"CNHMUNI", numeric:"MTD4054"},
{name:"Curtis Meadow <span class=\"amp\">&amp;</span> Staley", ident:"CTSMDWSTLY", numeric:"MTD2570"},
{name:"Curtis Road <span class=\"amp\">&amp;</span> South First St.", ident:"CTS1ST", numeric:"MTD4113"},
{name:"Dodson <span class=\"amp\">&amp;</span> Illinois", ident:"DDSNIL", numeric:"MTD1670"},
{name:"Dodson <span class=\"amp\">&amp;</span> Nevada", ident:"DDSNNV", numeric:"MTD6226"},
{name:"Dorner <span class=\"amp\">&amp;</span> Peabody", ident:"DNRPDY", numeric:"MTD3445"},
{name:"Duncan <span class=\"amp\">&amp;</span> Clark", ident:"DNCNCLKRD", numeric:"MTD3333"},
{name:"Duncan <span class=\"amp\">&amp;</span> Clayton", ident:"DNCNCLTN", numeric:"MTD2633"},
{name:"Duncan <span class=\"amp\">&amp;</span> Crestridge", ident:"DNCNCSTRG", numeric:"MTD3061"},
{name:"Duncan <span class=\"amp\">&amp;</span> Crossing Ct.", ident:"DNCNCRSNG", numeric:"MTD1600"},
{name:"Duncan <span class=\"amp\">&amp;</span> Curtis", ident:"DNCNCTS", numeric:"MTD6742"},
{name:"Duncan <span class=\"amp\">&amp;</span> Heathwood Ct.", ident:"DNCNHTWD", numeric:"MTD2617"},
{name:"Duncan <span class=\"amp\">&amp;</span> Lager", ident:"DNCNLGR", numeric:"MTD4543"},
{name:"Duncan <span class=\"amp\">&amp;</span> Meadows West", ident:"DNCNMWW", numeric:"MTD0562"},
{name:"Duncan <span class=\"amp\">&amp;</span> Prairie Meadow", ident:"DNCNPMDW", numeric:"MTD3371"},
{name:"Duncan <span class=\"amp\">&amp;</span> Rolling Acres", ident:"DNCNRLACR", numeric:"MTD4653"},
{name:"Duncan <span class=\"amp\">&amp;</span> Stoneybrook", ident:"DNCNSTNBK", numeric:"MTD0411"},
{name:"Duncan <span class=\"amp\">&amp;</span> Valleybrook", ident:"DNCNVYBK", numeric:"MTD6170"},
{name:"Duncan <span class=\"amp\">&amp;</span> Wedgewood", ident:"DNCNWDGWD", numeric:"MTD7015"},
{name:"Elm <span class=\"amp\">&amp;</span> Park", ident:"ELMPK", numeric:"MTD6542"},
{name:"FAR", ident:"FAR", numeric:"MTD1366"},
{name:"Fairlawn <span class=\"amp\">&amp;</span> Cottage Grove", ident:"FRLNCTGRV", numeric:"MTD0243"},
{name:"Fairview <span class=\"amp\">&amp;</span> Busey", ident:"FRVWBUSEY", numeric:"MTD5761"},
{name:"Fairview <span class=\"amp\">&amp;</span> Goodwin", ident:"FRVWGWN", numeric:"MTD0724"},
{name:"Fairview <span class=\"amp\">&amp;</span> Gregory", ident:"FRVWGRG", numeric:"MTD5224"},
{name:"Fairview <span class=\"amp\">&amp;</span> Lincoln", ident:"FRVWLNCLN", numeric:"MTD1465"},
{name:"Farber <span class=\"amp\">&amp;</span> Newton", ident:"FRBRNWTN", numeric:"MTD5114"},
{name:"Fifth <span class=\"amp\">&amp;</span> Armory", ident:"5THARY", numeric:"MTD5517"},
{name:"Fifth <span class=\"amp\">&amp;</span> Beardsley", ident:"5THBRD", numeric:"MTD2054"},
{name:"Fifth <span class=\"amp\">&amp;</span> Bradley", ident:"5THBRAD", numeric:"MTD5452"},
{name:"Fifth <span class=\"amp\">&amp;</span> Chalmers", ident:"5THCHAL", numeric:"MTD7555"},
{name:"Fifth <span class=\"amp\">&amp;</span> Columbia", ident:"5THCLMBA", numeric:"MTD2036"},
{name:"Fifth <span class=\"amp\">&amp;</span> Eureka", ident:"5THERKA", numeric:"MTD1232"},
{name:"Fifth <span class=\"amp\">&amp;</span> Grove", ident:"5THGRV", numeric:"MTD2337"},
{name:"Fifth <span class=\"amp\">&amp;</span> Tremont", ident:"5THTRMNT", numeric:"MTD4102"},
{name:"Fifth <span class=\"amp\">&amp;</span> Vine", ident:"5THVIN", numeric:"MTD1255"},
{name:"Fifth <span class=\"amp\">&amp;</span> Washington", ident:"5THWASH", numeric:"MTD5571"},
{name:"First <span class=\"amp\">&amp;</span> Armory", ident:"1STARY", numeric:"MTD6236"},
{name:"First <span class=\"amp\">&amp;</span> Chalmers", ident:"1STCHAL", numeric:"MTD5234"},
{name:"First <span class=\"amp\">&amp;</span> Chester", ident:"1STCHSTR", numeric:"MTD6635"},
{name:"First <span class=\"amp\">&amp;</span> Clark", ident:"1STCLARK", numeric:"MTD3657"},
{name:"First <span class=\"amp\">&amp;</span> Daniel", ident:"1STDAN", numeric:"MTD4361"},
{name:"First <span class=\"amp\">&amp;</span> Gregory", ident:"1STGRG", numeric:"MTD5747"},
{name:"First <span class=\"amp\">&amp;</span> Hazelwood", ident:"1STHZLWD", numeric:"MTD0342"},
{name:"First <span class=\"amp\">&amp;</span> Healey", ident:"1STHLY", numeric:"MTD6026"},
{name:"First <span class=\"amp\">&amp;</span> John", ident:"1STJOHN", numeric:"MTD4212"},
{name:"First <span class=\"amp\">&amp;</span> Northeast Lot E-14", ident:"1NE14", numeric:"MTD5562"},
{name:"First <span class=\"amp\">&amp;</span> Peabody", ident:"1STPDY", numeric:"MTD3246"},
{name:"First <span class=\"amp\">&amp;</span> Southeast Lot E-14", ident:"1STE14", numeric:"MTD4247"},
{name:"First <span class=\"amp\">&amp;</span> Springfield", ident:"1STSPFLD", numeric:"MTD5677"},
{name:"First <span class=\"amp\">&amp;</span> St. Mary's Rd.", ident:"1STSMR", numeric:"MTD1333"},
{name:"First <span class=\"amp\">&amp;</span> Stadium", ident:"1STSTDM", numeric:"MTD1756"},
{name:"First <span class=\"amp\">&amp;</span> Stoughton", ident:"1STSTOTN", numeric:"MTD2244"},
{name:"First <span class=\"amp\">&amp;</span> Windsor", ident:"1STWDSR", numeric:"MTD5610"},
{name:"First at Ashton Woods", ident:"ASHTON", numeric:"MTD4235"},
{name:"First at Swine Research Facility", ident:"SWINE", numeric:"MTD0363"},
{name:"First at University of Illinois Research Park", ident:"1STUIRP", numeric:"MTD4705"},
{name:"Florida <span class=\"amp\">&amp;</span> Adams", ident:"FLADAMS", numeric:"MTD6516"},
{name:"Florida <span class=\"amp\">&amp;</span> Anderson", ident:"FLADRSN", numeric:"MTD5305"},
{name:"Florida <span class=\"amp\">&amp;</span> Broadway", ident:"FLBRDWY", numeric:"MTD4031"},
{name:"Florida <span class=\"amp\">&amp;</span> Busey", ident:"FLBUSEY", numeric:"MTD7201"},
{name:"Florida <span class=\"amp\">&amp;</span> Cottage Grove", ident:"FLCTGRV", numeric:"MTD2252"},
{name:"Florida <span class=\"amp\">&amp;</span> Curtiss", ident:"FLCRTS", numeric:"MTD1462"},
{name:"Florida <span class=\"amp\">&amp;</span> Florida Ct.", ident:"FLFLCT", numeric:"MTD2174"},
{name:"Florida <span class=\"amp\">&amp;</span> Florida Dr.", ident:"FLFLDR", numeric:"MTD4711"},
{name:"Florida <span class=\"amp\">&amp;</span> Grove", ident:"FLGRV", numeric:"MTD4206"},
{name:"Florida <span class=\"amp\">&amp;</span> Hillcrest", ident:"FLHLCRST", numeric:"MTD6752"},
{name:"Florida <span class=\"amp\">&amp;</span> James Cherry", ident:"FLJASCHER", numeric:"MTD5736"},
{name:"Florida <span class=\"amp\">&amp;</span> Kinch", ident:"FLKNCH", numeric:"MTD0113"},
{name:"Florida <span class=\"amp\">&amp;</span> Lincoln", ident:"FLLNCLN", numeric:"MTD6352"},
{name:"Florida <span class=\"amp\">&amp;</span> Lincolnwood", ident:"FLLCLNWD", numeric:"MTD7456"},
{name:"Florida <span class=\"amp\">&amp;</span> Linden", ident:"FLLNDN", numeric:"MTD2543"},
{name:"Florida <span class=\"amp\">&amp;</span> Maple", ident:"FLMPL", numeric:"MTD5311"},
{name:"Florida <span class=\"amp\">&amp;</span> Orchard", ident:"FLOD", numeric:"MTD1151"},
{name:"Florida <span class=\"amp\">&amp;</span> Philo", ident:"FLPHILO", numeric:"MTD7036"},
{name:"Florida <span class=\"amp\">&amp;</span> Pleasant Dr.", ident:"FLPLSNT", numeric:"MTD6751"},
{name:"Florida <span class=\"amp\">&amp;</span> Race", ident:"FLRACE", numeric:"MTD1672"},
{name:"Florida <span class=\"amp\">&amp;</span> Rutledge", ident:"FLRTLG", numeric:"MTD2323"},
{name:"Florida <span class=\"amp\">&amp;</span> Smith", ident:"FLSMITH", numeric:"MTD3565"},
{name:"Florida <span class=\"amp\">&amp;</span> Vine", ident:"FLVIN", numeric:"MTD4306"},
{name:"Florida <span class=\"amp\">&amp;</span> Wiley", ident:"FLWLY", numeric:"MTD3444"},
{name:"Florida at Sunnycrest Apts.", ident:"FLSUNAPTS", numeric:"MTD3632"},
{name:"Fourth <span class=\"amp\">&amp;</span> Armory", ident:"4THARY", numeric:"MTD5576"},
{name:"Fourth <span class=\"amp\">&amp;</span> Bradley", ident:"4THBRAD", numeric:"MTD7716"},
{name:"Fourth <span class=\"amp\">&amp;</span> Chalmers", ident:"4THCHAL", numeric:"MTD4752"},
{name:"Fourth <span class=\"amp\">&amp;</span> Daniel", ident:"4THDAN", numeric:"MTD4047"},
{name:"Fourth <span class=\"amp\">&amp;</span> Gregory", ident:"4THGRG", numeric:"MTD1411"},
{name:"Fourth <span class=\"amp\">&amp;</span> John", ident:"4THJOHN", numeric:"MTD5423"},
{name:"Fourth <span class=\"amp\">&amp;</span> Kirby", ident:"4THKBY", numeric:"MTD6675"},
{name:"Fourth <span class=\"amp\">&amp;</span> Peabody", ident:"4THPDY", numeric:"MTD3014"},
{name:"Fourth <span class=\"amp\">&amp;</span> Pennsylvania", ident:"4THPA", numeric:"MTD6735"},
{name:"Fourth <span class=\"amp\">&amp;</span> Springfield", ident:"4THSPFLD", numeric:"MTD3141"},
{name:"Fourth <span class=\"amp\">&amp;</span> St. Mary's", ident:"4THSMR", numeric:"MTD7424"},
{name:"Fox Drive <span class=\"amp\">&amp;</span> StateSt.", ident:"FOXSTE", numeric:"MTD0700"},
{name:"Fox Drive at State Universities Retirement System", ident:"FOXSURS", numeric:"MTD5130"},
{name:"Goodwin <span class=\"amp\">&amp;</span> Church", ident:"GWNCHCH", numeric:"MTD5643"},
{name:"Goodwin <span class=\"amp\">&amp;</span> Clark", ident:"GWNCLK", numeric:"MTD7312"},
{name:"Goodwin <span class=\"amp\">&amp;</span> Gregory", ident:"GWNGRG", numeric:"MTD2554"},
{name:"Goodwin <span class=\"amp\">&amp;</span> Hill", ident:"GWNHIL", numeric:"MTD3643"},
{name:"Goodwin <span class=\"amp\">&amp;</span> Illinois", ident:"GWNIL", numeric:"MTD6164"},
{name:"Goodwin <span class=\"amp\">&amp;</span> Main", ident:"GWNMN", numeric:"MTD6051"},
{name:"Goodwin <span class=\"amp\">&amp;</span> Nevada", ident:"GWNNV", numeric:"MTD1242"},
{name:"Goodwin <span class=\"amp\">&amp;</span> Oregon", ident:"GWNOR", numeric:"MTD5513"},
{name:"Goodwin <span class=\"amp\">&amp;</span> Park", ident:"GWNPK", numeric:"MTD6575"},
{name:"Goodwin <span class=\"amp\">&amp;</span> Springfield", ident:"GWNSPFLD", numeric:"MTD4327"},
{name:"Goodwin <span class=\"amp\">&amp;</span> Stoughton", ident:"GWNSTOTN", numeric:"MTD7110"},
{name:"Goodwin at Ceramics Building", ident:"GDWNCB", numeric:"MTD0156"},
{name:"Goodwin at Krannert - Westside", ident:"CHEMLS", numeric:"MTD6242"},
{name:"Goodwin at Materials Research Laboritory", ident:"GDWNMRL", numeric:"MTD2360"},
{name:"Green <span class=\"amp\">&amp;</span> Anderson", ident:"GRNADRSN", numeric:"MTD2612"},
{name:"Green <span class=\"amp\">&amp;</span> Birch", ident:"GRNBRCH", numeric:"MTD4061"},
{name:"Green <span class=\"amp\">&amp;</span> Busey", ident:"GRNBUSEY", numeric:"MTD6726"},
{name:"Green <span class=\"amp\">&amp;</span> Cedar", ident:"GRNCDR", numeric:"MTD3552"},
{name:"Green <span class=\"amp\">&amp;</span> Coler", ident:"GRNCLR", numeric:"MTD4343"},
{name:"Green <span class=\"amp\">&amp;</span> Fourth", ident:"GRN4TH", numeric:"MTD3311"},
{name:"Green <span class=\"amp\">&amp;</span> Goodwin", ident:"GRNGWN", numeric:"MTD4360"},
{name:"Green <span class=\"amp\">&amp;</span> Gregory St.", ident:"GRNGRGST", numeric:"MTD2264"},
{name:"Green <span class=\"amp\">&amp;</span> Grove", ident:"GRNGRV", numeric:"MTD4642"},
{name:"Green <span class=\"amp\">&amp;</span> Johnson", ident:"GRNJNSN", numeric:"MTD6423"},
{name:"Green <span class=\"amp\">&amp;</span> Lincoln", ident:"GRNLNCLN", numeric:"MTD4201"},
{name:"Green <span class=\"amp\">&amp;</span> Locust", ident:"GRNLCST", numeric:"MTD3544"},
{name:"Green <span class=\"amp\">&amp;</span> Lynn", ident:"GRNLYN", numeric:"MTD3243"},
{name:"Green <span class=\"amp\">&amp;</span> Mathews", ident:"GRNMAT", numeric:"MTD5415"},
{name:"Green <span class=\"amp\">&amp;</span> McCullough", ident:"GRNMCLGH", numeric:"MTD5265"},
{name:"Green <span class=\"amp\">&amp;</span> Neil", ident:"GRNNEIL", numeric:"MTD3336"},
{name:"Green <span class=\"amp\">&amp;</span> Orchard", ident:"GRNORCH", numeric:"MTD3617"},
{name:"Green <span class=\"amp\">&amp;</span> Prairie", ident:"GRNPRRE", numeric:"MTD1370"},
{name:"Green <span class=\"amp\">&amp;</span> Prospect", ident:"GRNPSPCT", numeric:"MTD7175"},
{name:"Green <span class=\"amp\">&amp;</span> Race", ident:"GRNRACE", numeric:"MTD2303"},
{name:"Green <span class=\"amp\">&amp;</span> Randolph", ident:"GRNRNDLF", numeric:"MTD5246"},
{name:"Green <span class=\"amp\">&amp;</span> Second", ident:"GRN2ND", numeric:"MTD6431"},
{name:"Green <span class=\"amp\">&amp;</span> Sixth", ident:"GRN6TH", numeric:"MTD3343"},
{name:"Green <span class=\"amp\">&amp;</span> State", ident:"GRNSTE", numeric:"MTD4103"},
{name:"Green <span class=\"amp\">&amp;</span> Urbana", ident:"GRNUBNA", numeric:"MTD6322"},
{name:"Green <span class=\"amp\">&amp;</span> Vine", ident:"GRNVIN", numeric:"MTD5661"},
{name:"Green <span class=\"amp\">&amp;</span> Webber", ident:"GRNWBR", numeric:"MTD4341"},
{name:"Green <span class=\"amp\">&amp;</span> Wright", ident:"GRNWRT", numeric:"MTD6456"},
{name:"Green at Daniels Hall", ident:"GRNDANHALL", numeric:"MTD2374"},
{name:"Green at Illinos Street Residence Hall", ident:"GRNISR", numeric:"MTD2472"},
{name:"Gregory <span class=\"amp\">&amp;</span> Arbor", ident:"GRGARB", numeric:"MTD1562"},
{name:"Gregory <span class=\"amp\">&amp;</span> Dorner", ident:"GRGDNR", numeric:"MTD2451"},
{name:"Gregory <span class=\"amp\">&amp;</span> Euclid", ident:"GRGECLD", numeric:"MTD4262"},
{name:"Gregory <span class=\"amp\">&amp;</span> Oak", ident:"GRGOAK", numeric:"MTD6622"},
{name:"Gregory <span class=\"amp\">&amp;</span> Second St", ident:"GRG2ND", numeric:"MTD3460"},
{name:"Gregory Place <span class=\"amp\">&amp;</span> Oregon", ident:"GRGPLOR", numeric:"MTD4221"},
{name:"Gregory at Library", ident:"GRGLIB", numeric:"MTD1455"},
{name:"Gregory at Mumford Hall", ident:"GRGMUM", numeric:"MTD2624"},
{name:"Gregory at Personnel Services", ident:"GRGPS", numeric:"MTD5612"},
{name:"Gren <span class=\"amp\">&amp;</span> Maple", ident:"GRNMPL", numeric:"MTD1347"},
{name:"Harris <span class=\"amp\">&amp;</span> Maple", ident:"HRISMPL", numeric:"MTD2225"},
{name:"Hazelwood <span class=\"amp\">&amp;</span> Oak", ident:"HZLWDOAK", numeric:"MTD2170"},
{name:"Hessel <span class=\"amp\">&amp;</span> Randolph", ident:"HSLRNDLF", numeric:"MTD4112"},
{name:"Highcross <span class=\"amp\">&amp;</span> Apostalic Life Church", ident:"HICRSALC", numeric:"MTD2411"},
{name:"I.E.T.C. <span class=\"amp\">&amp;</span> Mattis", ident:"IETCMATS", numeric:"MTD3253"},
{name:"Illini Union Engineering Side", ident:"IUE", numeric:"MTD2115"},
{name:"Illini Union", ident:"IU", numeric:"MTD6451"},
{name:"Illinois <span class=\"amp\">&amp;</span> Broadway", ident:"ILBDWY", numeric:"MTD4014"},
{name:"Illinois <span class=\"amp\">&amp;</span> Glenn Dr.", ident:"ILGLN", numeric:"MTD3272"},
{name:"Illinois Employment Training Center", ident:"IETC", numeric:"MTD1412"},
{name:"Illinois Power", ident:"IP", numeric:"MTD4716"},
{name:"Illinois Terminal (Platform A)", ident:"IT", numeric:"MTD7534"},
{name:"Illinois Terminal (Platform B)", ident:"IT", numeric:"MTD6462"},
{name:"Illinois Terminal at Market St.", ident:"ITMKT", numeric:"MTD3154"},
{name:"Illinois Terminal", ident:"IT", numeric:"MTD3121"},
{name:"Interstate <span class=\"amp\">&amp;</span> Farber", ident:"INTFRBR", numeric:"MTD5173"},
{name:"Interstate at First Step", ident:"INT1STSTP", numeric:"MTD2551"},
{name:"Ironwood <span class=\"amp\">&amp;</span> Staley", ident:"IRNWDSTLY", numeric:"MTD6577"},
{name:"John <span class=\"amp\">&amp;</span> Duncan", ident:"JOHNDNCN", numeric:"MTD3362"},
{name:"John <span class=\"amp\">&amp;</span> Kenwood", ident:"JOHNKNWD", numeric:"MTD1573"},
{name:"John <span class=\"amp\">&amp;</span> Lynn", ident:"JOHNLYN", numeric:"MTD1251"},
{name:"John <span class=\"amp\">&amp;</span> Mattis", ident:"JOHNMATS", numeric:"MTD3747"},
{name:"John <span class=\"amp\">&amp;</span> Prospect", ident:"JOHNPSPCT", numeric:"MTD7703"},
{name:"John <span class=\"amp\">&amp;</span> Western", ident:"JOHNWSTRN", numeric:"MTD5441"},
{name:"Kirby <span class=\"amp\">&amp;</span> Alma", ident:"KBYALMA", numeric:"MTD3423"},
{name:"Kirby <span class=\"amp\">&amp;</span> Arrow Rd.", ident:"KBYARW", numeric:"MTD4331"},
{name:"Kirby <span class=\"amp\">&amp;</span> Bellepark Dr.", ident:"KBYBLPK", numeric:"MTD2614"},
{name:"Kirby <span class=\"amp\">&amp;</span> Cambridge", ident:"KBYCMBG", numeric:"MTD2652"},
{name:"Kirby <span class=\"amp\">&amp;</span> Carolyn", ident:"KBYCAROL", numeric:"MTD5512"},
{name:"Kirby <span class=\"amp\">&amp;</span> Carriage Way", ident:"KBYCRGWY", numeric:"MTD4424"},
{name:"Kirby <span class=\"amp\">&amp;</span> Carriage Way", ident:"KBYCRRGWY", numeric:"MTD1346"},
{name:"Kirby <span class=\"amp\">&amp;</span> Coronado", ident:"KBYCRNDO", numeric:"MTD5317"},
{name:"Kirby <span class=\"amp\">&amp;</span> Crescent", ident:"KBYCRSNT", numeric:"MTD4573"},
{name:"Kirby <span class=\"amp\">&amp;</span> Dawson", ident:"KBYDWSN", numeric:"MTD7226"},
{name:"Kirby <span class=\"amp\">&amp;</span> Dodds", ident:"KBYDODD", numeric:"MTD2217"},
{name:"Kirby <span class=\"amp\">&amp;</span> Duncan", ident:"KBYDNCN", numeric:"MTD4075"},
{name:"Kirby <span class=\"amp\">&amp;</span> First", ident:"KBY1ST", numeric:"MTD5212"},
{name:"Kirby <span class=\"amp\">&amp;</span> Grandview Dr. E.", ident:"KBYGDVWE", numeric:"MTD5261"},
{name:"Kirby <span class=\"amp\">&amp;</span> Grandview Dr. W.", ident:"KBYGDVWW", numeric:"MTD0732"},
{name:"Kirby <span class=\"amp\">&amp;</span> Greencroft", ident:"KBYGRNCFT", numeric:"MTD6250"},
{name:"Kirby <span class=\"amp\">&amp;</span> IGA Store", ident:"KBYIGA", numeric:"MTD4425"},
{name:"Kirby <span class=\"amp\">&amp;</span> Kenwood", ident:"KBYKNWD", numeric:"MTD3441"},
{name:"Kirby <span class=\"amp\">&amp;</span> Lincoln Rd.", ident:"KBYLCLNRD", numeric:"MTD2524"},
{name:"Kirby <span class=\"amp\">&amp;</span> Mattis", ident:"KBYMATS", numeric:"MTD7267"},
{name:"Kirby <span class=\"amp\">&amp;</span> Mayfair", ident:"KBYMYFR", numeric:"MTD4151"},
{name:"Kirby <span class=\"amp\">&amp;</span> Mullikin", ident:"KRBYMLKN", numeric:"MTD5413"},
{name:"Kirby <span class=\"amp\">&amp;</span> Neil", ident:"KBYNEIL", numeric:"MTD7513"},
{name:"Kirby <span class=\"amp\">&amp;</span> Oak", ident:"KBYOAK", numeric:"MTD3232"},
{name:"Kirby <span class=\"amp\">&amp;</span> Park Haven", ident:"KBYPRKHVN", numeric:"MTD5614"},
{name:"Kirby <span class=\"amp\">&amp;</span> Ridge Rd.", ident:"KBYRDGRD", numeric:"MTD3317"},
{name:"Kirby <span class=\"amp\">&amp;</span> Rose Dr.", ident:"KBYROSE", numeric:"MTD1542"},
{name:"Kirby <span class=\"amp\">&amp;</span> Rosewood", ident:"KBYRSWD", numeric:"MTD3201"},
{name:"Kirby <span class=\"amp\">&amp;</span> Scottsdale", ident:"KBYSCTDL", numeric:"MTD3111"},
{name:"Kirby <span class=\"amp\">&amp;</span> State", ident:"KBYSTE", numeric:"MTD3263"},
{name:"Kirby <span class=\"amp\">&amp;</span> Stratford", ident:"KBYSRTFRD", numeric:"MTD5162"},
{name:"Kirby <span class=\"amp\">&amp;</span> Valley Rd.", ident:"KBYVYRD", numeric:"MTD6333"},
{name:"Kirby <span class=\"amp\">&amp;</span> Waverly", ident:"KBYWAVE", numeric:"MTD0331"},
{name:"Kirby <span class=\"amp\">&amp;</span> Western", ident:"KBYWSTRN", numeric:"MTD1332"},
{name:"Kirby <span class=\"amp\">&amp;</span> Westfield", ident:"KBYWSFLD", numeric:"MTD4346"},
{name:"Krannert Center", ident:"KRANNERT", numeric:"MTD0543"},
{name:"Lincoln <span class=\"amp\">&amp;</span> Anthony", ident:"LNCLNANT", numeric:"MTD7321"},
{name:"Lincoln <span class=\"amp\">&amp;</span> Bradley", ident:"LNCLNBRAD", numeric:"MTD1652"},
{name:"Lincoln <span class=\"amp\">&amp;</span> California", ident:"LNCLNCA", numeric:"MTD3651"},
{name:"Lincoln <span class=\"amp\">&amp;</span> Church", ident:"LNCLNCHCH", numeric:"MTD2126"},
{name:"Lincoln <span class=\"amp\">&amp;</span> Clark", ident:"LNCLNCLARK", numeric:"MTD6750"},
{name:"Lincoln <span class=\"amp\">&amp;</span> College Ct.", ident:"LNCLNCC", numeric:"MTD5252"},
{name:"Lincoln <span class=\"amp\">&amp;</span> Delaware", ident:"LNCLNDE", numeric:"MTD3110"},
{name:"Lincoln <span class=\"amp\">&amp;</span> Eads", ident:"LNCLNEADS", numeric:"MTD3532"},
{name:"Lincoln <span class=\"amp\">&amp;</span> Florida", ident:"LNCLNFL", numeric:"MTD5540"},
{name:"Lincoln <span class=\"amp\">&amp;</span> Hill", ident:"LNCLNHIL", numeric:"MTD2547"},
{name:"Lincoln <span class=\"amp\">&amp;</span> Illinois", ident:"LNCLNIL", numeric:"MTD2434"},
{name:"Lincoln <span class=\"amp\">&amp;</span> Indiana", ident:"LNCLNIN", numeric:"MTD4601"},
{name:"Lincoln <span class=\"amp\">&amp;</span> Iowa", ident:"LNCLNIA", numeric:"MTD5231"},
{name:"Lincoln <span class=\"amp\">&amp;</span> Kettering Park", ident:"LNCLNKING", numeric:"MTD2261"},
{name:"Lincoln <span class=\"amp\">&amp;</span> Killarney", ident:"LNCLNKLRNY", numeric:"MTD4225"},
{name:"Lincoln <span class=\"amp\">&amp;</span> Main", ident:"LNCLNMN", numeric:"MTD1231"},
{name:"Lincoln <span class=\"amp\">&amp;</span> Michigan", ident:"LNCLNMI", numeric:"MTD6003"},
{name:"Lincoln <span class=\"amp\">&amp;</span> Ohio", ident:"LNCLNOH", numeric:"MTD2143"},
{name:"Lincoln <span class=\"amp\">&amp;</span> Oregon", ident:"LNCLNOR", numeric:"MTD1536"},
{name:"Lincoln <span class=\"amp\">&amp;</span> Park", ident:"LNCLNPK", numeric:"MTD5426"},
{name:"Lincoln <span class=\"amp\">&amp;</span> Pennsylvania", ident:"LNCLNPA", numeric:"MTD6321"},
{name:"Lincoln <span class=\"amp\">&amp;</span> St. Marys Rd", ident:"LNCLNSMR", numeric:"MTD7337"},
{name:"Lincoln <span class=\"amp\">&amp;</span> Stoughton", ident:"LNCLNSTOTN", numeric:"MTD4355"},
{name:"Lincoln <span class=\"amp\">&amp;</span> Sunset", ident:"LNCLNSNST", numeric:"MTD6212"},
{name:"Lincoln <span class=\"amp\">&amp;</span> Vermont", ident:"LNCLNVT", numeric:"MTD0112"},
{name:"Lincoln <span class=\"amp\">&amp;</span> Wascher", ident:"LNCLNWSCR", numeric:"MTD4540"},
{name:"Lincoln Ave. Residence Hall", ident:"LAR", numeric:"MTD2006"},
{name:"Lincoln Square (Courthouse)", ident:"LSE", numeric:"MTD5137"},
{name:"Lincoln Square (Parking Garage)", ident:"LSG", numeric:"MTD6514"},
{name:"Lincoln View Apts", ident:"UNICMNS", numeric:"MTD1141"},
{name:"Lincoln at Hazelwood", ident:"LNCLNHZLWD", numeric:"MTD2642"},
{name:"Lincoln at Japan House", ident:"JPN", numeric:"MTD7551"},
{name:"Lincolnshire <span class=\"amp\">&amp;</span> Foothill", ident:"LCNSRFTHL", numeric:"MTD7142"},
{name:"Lincolnshire <span class=\"amp\">&amp;</span> Foothill", ident:"LNCSRFTHL", numeric:"MTD2276"},
{name:"Lincolnwood <span class=\"amp\">&amp;</span> Michigan", ident:"LNCLNWDMI", numeric:"MTD1525"},
{name:"Logan <span class=\"amp\">&amp;</span> First", ident:"LGN1ST", numeric:"MTD1662"},
{name:"Logan <span class=\"amp\">&amp;</span> Neil", ident:"LGNNEIL", numeric:"MTD5104"},
{name:"Logan <span class=\"amp\">&amp;</span> Water", ident:"LGNWTR", numeric:"MTD5510"},
{name:"Lot E-14", ident:"E14", numeric:"MTD3513"},
{name:"Lyndhurst <span class=\"amp\">&amp;</span> Old Maple Lane", ident:"LNHSTOML", numeric:"MTD5520"},
{name:"Lyndhurst <span class=\"amp\">&amp;</span> Park Lane", ident:"LNHSTPKLN", numeric:"MTD5712"},
{name:"MacArthur <span class=\"amp\">&amp;</span> California", ident:"MCRTRCA", numeric:"MTD7505"},
{name:"MacArthur <span class=\"amp\">&amp;</span> Illinois", ident:"MCRTRIL", numeric:"MTD4462"},
{name:"Main <span class=\"amp\">&amp;</span> Art Bartell Dr.", ident:"MNABD", numeric:"MTD2561"},
{name:"Main <span class=\"amp\">&amp;</span> Brady", ident:"MNBRDY", numeric:"MTD6357"},
{name:"Main <span class=\"amp\">&amp;</span> Broadway", ident:"MNBDWY", numeric:"MTD3663"},
{name:"Main <span class=\"amp\">&amp;</span> Broadway", ident:"MNBRDWY", numeric:"MTD2201"},
{name:"Main <span class=\"amp\">&amp;</span> Chestnut", ident:"MNCHSNT", numeric:"MTD0765"},
{name:"Main <span class=\"amp\">&amp;</span> Cottage Grove", ident:"MNCTGRV", numeric:"MTD4532"},
{name:"Main <span class=\"amp\">&amp;</span> Dewey", ident:"MNDWY", numeric:"MTD6201"},
{name:"Main <span class=\"amp\">&amp;</span> Dodson", ident:"MNDDSN", numeric:"MTD3104"},
{name:"Main <span class=\"amp\">&amp;</span> Ennis", ident:"MNENIS", numeric:"MTD6306"},
{name:"Main <span class=\"amp\">&amp;</span> Fremont", ident:"MNFREMNT", numeric:"MTD3452"},
{name:"Main <span class=\"amp\">&amp;</span> Glover", ident:"MNGLVR", numeric:"MTD1663"},
{name:"Main <span class=\"amp\">&amp;</span> Grove", ident:"MNGRV", numeric:"MTD4246"},
{name:"Main <span class=\"amp\">&amp;</span> Hartle", ident:"MNHTL", numeric:"MTD4754"},
{name:"Main <span class=\"amp\">&amp;</span> Lierman", ident:"MNLRMN", numeric:"MTD0660"},
{name:"Main <span class=\"amp\">&amp;</span> Lynn", ident:"MNLYN", numeric:"MTD5574"},
{name:"Main <span class=\"amp\">&amp;</span> Maple", ident:"MNMPL", numeric:"MTD6561"},
{name:"Main <span class=\"amp\">&amp;</span> Market", ident:"MNMKT", numeric:"MTD6173"},
{name:"Main <span class=\"amp\">&amp;</span> Poplar", ident:"MNPLR", numeric:"MTD3140"},
{name:"Main <span class=\"amp\">&amp;</span> Scottswood", ident:"MNSCWD", numeric:"MTD4515"},
{name:"Main <span class=\"amp\">&amp;</span> Smith Rd.", ident:"MNSMITH", numeric:"MTD4421"},
{name:"Main <span class=\"amp\">&amp;</span> U.S. Route 150", ident:"MN150", numeric:"MTD1014"},
{name:"Main <span class=\"amp\">&amp;</span> Urbana", ident:"MNUBNA", numeric:"MTD1645"},
{name:"Main <span class=\"amp\">&amp;</span> Vine", ident:"MNVIN", numeric:"MTD4205"},
{name:"Main <span class=\"amp\">&amp;</span> Walnut", ident:"MNWLNT", numeric:"MTD3630"},
{name:"Main <span class=\"amp\">&amp;</span> Webber", ident:"MNWBR", numeric:"MTD6613"},
{name:"Maplepark <span class=\"amp\">&amp;</span> Alton", ident:"MPLPKALTN", numeric:"MTD2145"},
{name:"Maplepark <span class=\"amp\">&amp;</span> Carrelton", ident:"MPLPKCRLTN", numeric:"MTD1267"},
{name:"Maplepark <span class=\"amp\">&amp;</span> Lawndale", ident:"MPLPKLWNDL", numeric:"MTD2146"},
{name:"Maplepark <span class=\"amp\">&amp;</span> Maplewood", ident:"MPLPKMPLWD", numeric:"MTD4441"},
{name:"Maplepark <span class=\"amp\">&amp;</span> Sangamon", ident:"MPLPKSANG", numeric:"MTD5201"},
{name:"Maplepark <span class=\"amp\">&amp;</span> William", ident:"MPLPKWLM", numeric:"MTD0563"},
{name:"Maplepark <span class=\"amp\">&amp;</span> Willowpark", ident:"MPLPKWLPK", numeric:"MTD7474"},
{name:"Market <span class=\"amp\">&amp;</span> University", ident:"MKTUNI", numeric:"MTD7133"},
{name:"Maryland <span class=\"amp\">&amp;</span> College Ct", ident:"MDCC", numeric:"MTD3606"},
{name:"Mathews &amp; Nevada", ident:"MATNV", numeric:"MTD4467"},
{name:"Mathews <span class=\"amp\">&amp;</span> Oregon", ident:"MATOR", numeric:"MTD3053"},
{name:"Mathews at Gazebo Shelter", ident:"MATGAZ", numeric:"MTD4634"},
{name:"Mattis <span class=\"amp\">&amp;</span> Alton", ident:"MATSALTN", numeric:"MTD4776"},
{name:"Mattis <span class=\"amp\">&amp;</span> Anita", ident:"MATSANTA", numeric:"MTD2412"},
{name:"Mattis <span class=\"amp\">&amp;</span> Anthony", ident:"MATSANT", numeric:"MTD7254"},
{name:"Mattis <span class=\"amp\">&amp;</span> Bloomington", ident:"MATSBLOM", numeric:"MTD4722"},
{name:"Mattis <span class=\"amp\">&amp;</span> Branch Rd.", ident:"MATSBRCH", numeric:"MTD2436"},
{name:"Mattis <span class=\"amp\">&amp;</span> Broadmoor", ident:"MATSBDMR", numeric:"MTD6025"},
{name:"Mattis <span class=\"amp\">&amp;</span> Camp", ident:"MATSCAMP", numeric:"MTD6374"},
{name:"Mattis <span class=\"amp\">&amp;</span> Chevy Chase", ident:"MATSCHEVY", numeric:"MTD1354"},
{name:"Mattis <span class=\"amp\">&amp;</span> Cypress", ident:"MATSCYPS", numeric:"MTD6521"},
{name:"Mattis <span class=\"amp\">&amp;</span> Devonshire", ident:"MATSDVN", numeric:"MTD4566"},
{name:"Mattis <span class=\"amp\">&amp;</span> Gentry Square Ln. South", ident:"MATSGNSQ", numeric:"MTD1233"},
{name:"Mattis <span class=\"amp\">&amp;</span> Glenn Burne", ident:"MATSGBD", numeric:"MTD6525"},
{name:"Mattis <span class=\"amp\">&amp;</span> GlennPark Dr.", ident:"MATSGLNPK", numeric:"MTD3271"},
{name:"Mattis <span class=\"amp\">&amp;</span> Henry St.", ident:"MATSHNRY", numeric:"MTD3127"},
{name:"Mattis <span class=\"amp\">&amp;</span> Interstate", ident:"MATSINT", numeric:"MTD6565"},
{name:"Mattis <span class=\"amp\">&amp;</span> Ivy Ct. North", ident:"MATSIVYN", numeric:"MTD1504"},
{name:"Mattis <span class=\"amp\">&amp;</span> Ivy Ct. South", ident:"MATSIVYS", numeric:"MTD4436"},
{name:"Mattis <span class=\"amp\">&amp;</span> Meadow Dr.", ident:"MATSMDWDR", numeric:"MTD4511"},
{name:"Mattis <span class=\"amp\">&amp;</span> Princeton", ident:"MATSPRNCTN", numeric:"MTD1721"},
{name:"Mattis <span class=\"amp\">&amp;</span> Round barn RD.", ident:"MATSRBR", numeric:"MTD4073"},
{name:"Mattis <span class=\"amp\">&amp;</span> Sangamon", ident:"MATSSANG", numeric:"MTD4064"},
{name:"Mattis <span class=\"amp\">&amp;</span> Sheridan", ident:"MATSSHRDN", numeric:"MTD6301"},
{name:"Mattis <span class=\"amp\">&amp;</span> Southwood", ident:"MATSSTHWD", numeric:"MTD2313"},
{name:"Mattis <span class=\"amp\">&amp;</span> Springer", ident:"MATSSGR", numeric:"MTD4451"},
{name:"Mattis <span class=\"amp\">&amp;</span> Stonegate Dr.", ident:"MATSSTNGT", numeric:"MTD5653"},
{name:"Mattis <span class=\"amp\">&amp;</span> Sumac", ident:"MATSSMC", numeric:"MTD5527"},
{name:"Mattis <span class=\"amp\">&amp;</span> William", ident:"MATSWLM", numeric:"MTD2770"},
{name:"Mattis <span class=\"amp\">&amp;</span> Windsor", ident:"MATSWDSR", numeric:"MTD4143"},
{name:"Mattis at Garden Village", ident:"MATSGVA", numeric:"MTD1247"},
{name:"Mattis at Post Office", ident:"MATSUSPS", numeric:"MTD2521"},
{name:"Mattis at Schnucks", ident:"MATS", numeric:"MTD5705"},
{name:"Mayfair <span class=\"amp\">&amp;</span> Old Farm", ident:"MYFROF", numeric:"MTD7123"},
{name:"Maynard <span class=\"amp\">&amp;</span> Kirby", ident:"MYNRDKBY", numeric:"MTD6555"},
{name:"McHenry &amp; Lynn - East", ident:"MHRYLYNE", numeric:"MTD3321"},
{name:"McHenry <span class=\"amp\">&amp;</span> Anderson", ident:"MHRYADRSN", numeric:"MTD0062"},
{name:"McHenry <span class=\"amp\">&amp;</span> Cottage Grove", ident:"MHRYCTGRV", numeric:"MTD2714"},
{name:"McHenry <span class=\"amp\">&amp;</span> Lynn St. #2", ident:"MHRYLYN2", numeric:"MTD7331"},
{name:"McHenry <span class=\"amp\">&amp;</span> Lynn St. 1", ident:"MHRYLYN1", numeric:"MTD4443"},
{name:"McHenry <span class=\"amp\">&amp;</span> Lynn", ident:"MHRYLYN", numeric:"MTD2316"},
{name:"McKinley <span class=\"amp\">&amp;</span> Maple", ident:"MCNLYMPL", numeric:"MTD3060"},
{name:"Meijer Drive <span class=\"amp\">&amp;</span> Prospect", ident:"MJRPSPCT", numeric:"MTD2344"},
{name:"Meijer Drive at Meijer", ident:"MEIJER", numeric:"MTD2063"},
{name:"Michigan <span class=\"amp\">&amp;</span> Kinch", ident:"MIKNCH", numeric:"MTD0245"},
{name:"Michigan <span class=\"amp\">&amp;</span> Lincolnwood", ident:"MILNCLNWD", numeric:"MTD7661"},
{name:"Michigan <span class=\"amp\">&amp;</span> Smith", ident:"MISMITH", numeric:"MTD1315"},
{name:"Myra Ridge <span class=\"amp\">&amp;</span> Ridge Park", ident:"MYRARGPK", numeric:"MTD0142"},
{name:"Neil <span class=\"amp\">&amp;</span> Anthony Dr.", ident:"NEILANT", numeric:"MTD6140"},
{name:"Neil <span class=\"amp\">&amp;</span> Arbors Dr.", ident:"NEILARBR", numeric:"MTD2204"},
{name:"Neil <span class=\"amp\">&amp;</span> Arcadia", ident:"NEILARC", numeric:"MTD1632"},
{name:"Neil <span class=\"amp\">&amp;</span> Beardsley", ident:"NEILBRD", numeric:"MTD1451"},
{name:"Neil <span class=\"amp\">&amp;</span> Bellefontaine", ident:"NEILBELL", numeric:"MTD5634"},
{name:"Neil <span class=\"amp\">&amp;</span> Birch", ident:"NEILBRCH", numeric:"MTD2326"},
{name:"Neil <span class=\"amp\">&amp;</span> Bradley", ident:"NEILBRAD", numeric:"MTD4315"},
{name:"Neil <span class=\"amp\">&amp;</span> Buena Vista", ident:"NEILBV", numeric:"MTD4460"},
{name:"Neil <span class=\"amp\">&amp;</span> Burwash", ident:"NEILBRWS", numeric:"MTD5622"},
{name:"Neil <span class=\"amp\">&amp;</span> College Park Ct.", ident:"NEILCOLPK", numeric:"MTD5464"},
{name:"Neil <span class=\"amp\">&amp;</span> College Point Ct.", ident:"NEILCOLPT", numeric:"MTD7651"},
{name:"Neil <span class=\"amp\">&amp;</span> Columbia", ident:"NEILCLMBA", numeric:"MTD2553"},
{name:"Neil <span class=\"amp\">&amp;</span> Dunlap Ct.", ident:"NEILDNLP", numeric:"MTD3467"},
{name:"Neil <span class=\"amp\">&amp;</span> Edgebrook", ident:"NEILEGB", numeric:"MTD1133"},
{name:"Neil <span class=\"amp\">&amp;</span> Eureka", ident:"NEILERKA", numeric:"MTD0546"},
{name:"Neil <span class=\"amp\">&amp;</span> Garwood", ident:"NEILGAR", numeric:"MTD1142"},
{name:"Neil <span class=\"amp\">&amp;</span> Healey", ident:"NEILHLY", numeric:"MTD2041"},
{name:"Neil <span class=\"amp\">&amp;</span> Hessel", ident:"NEILHSL", numeric:"MTD6314"},
{name:"Neil <span class=\"amp\">&amp;</span> Hill St.", ident:"NEILHIL", numeric:"MTD2305"},
{name:"Neil <span class=\"amp\">&amp;</span> Interstate", ident:"NEILINTR", numeric:"MTD2740"},
{name:"Neil <span class=\"amp\">&amp;</span> Kenyon Road", ident:"NEILKNYN", numeric:"MTD6666"},
{name:"Neil <span class=\"amp\">&amp;</span> Knollwood", ident:"NEILKLWD", numeric:"MTD3257"},
{name:"Neil <span class=\"amp\">&amp;</span> Marketview", ident:"NEILMKTV", numeric:"MTD4650"},
{name:"Neil <span class=\"amp\">&amp;</span> Marshall", ident:"NEILMSHL", numeric:"MTD2362"},
{name:"Neil <span class=\"amp\">&amp;</span> North", ident:"NEILN", numeric:"MTD1613"},
{name:"Neil <span class=\"amp\">&amp;</span> Springfield", ident:"NEILSPFLD", numeric:"MTD6563"},
{name:"Neil <span class=\"amp\">&amp;</span> Stadium", ident:"NEILSTDM", numeric:"MTD4135"},
{name:"Neil <span class=\"amp\">&amp;</span> Vine", ident:"NEILVIN", numeric:"MTD4564"},
{name:"Neil <span class=\"amp\">&amp;</span> Walingford", ident:"NEILWLGFRD", numeric:"MTD3334"},
{name:"Neil <span class=\"amp\">&amp;</span> Washington", ident:"NEILWASH", numeric:"MTD6425"},
{name:"Neil <span class=\"amp\">&amp;</span> White", ident:"NEILWHT", numeric:"MTD3725"},
{name:"Nevada <span class=\"amp\">&amp;</span> Gregory Place", ident:"NVGRGPL", numeric:"MTD4044"},
{name:"Nevada <span class=\"amp\">&amp;</span> Lincoln", ident:"NVLNCLN", numeric:"MTD2463"},
{name:"Oak <span class=\"amp\">&amp;</span> Anthony", ident:"OAKANT", numeric:"MTD3155"},
{name:"Oak <span class=\"amp\">&amp;</span> Gerty", ident:"OAKGTY", numeric:"MTD1640"},
{name:"Oak <span class=\"amp\">&amp;</span> Kenyon", ident:"OAKKNYN", numeric:"MTD5025"},
{name:"Oak at Lot E-14", ident:"OAKE14", numeric:"MTD1157"},
{name:"Oak between Hazelwood <span class=\"amp\">&amp;</span> St. Mary's", ident:"OAK", numeric:"MTD1774"},
{name:"Orchard <span class=\"amp\">&amp;</span> George Huff", ident:"ODGHF", numeric:"MTD2311"},
{name:"Orchard Downs #1", ident:"OD", numeric:"MTD6530"},
{name:"Orchard Downs #2", ident:"OD", numeric:"MTD3134"},
{name:"Orchard Downs #3", ident:"OD", numeric:"MTD2534"},
{name:"Orchard Downs #4", ident:"OD", numeric:"MTD6447"},
{name:"Orchard Downs North Shelter", ident:"ODNS", numeric:"MTD3214"},
{name:"Orchard Downs South Shelter", ident:"ODSS", numeric:"MTD7317"},
{name:"PAR", ident:"PAR", numeric:"MTD5524"},
{name:"PARKVIEW", ident:"PARKVIEW", numeric:"MTD1340"},
{name:"Paddock Dr. East <span class=\"amp\">&amp;</span> Lot C", ident:"PDKELOTC", numeric:"MTD1737"},
{name:"Paddock Dr. East <span class=\"amp\">&amp;</span> Lot E", ident:"PDKELOTE", numeric:"MTD2211"},
{name:"Paddock Dr. East at Winfeld Village Lot D", ident:"PDKELOTD", numeric:"MTD2703"},
{name:"Paddock Dr. East at Winfield Village Lot B", ident:"PDKELOTB", numeric:"MTD6033"},
{name:"Paddock Dr. West <span class=\"amp\">&amp;</span> Lot J", ident:"PDKWLOTJ", numeric:"MTD1147"},
{name:"Paddock Dr. West <span class=\"amp\">&amp;</span> Lot L", ident:"PDKWLOTL", numeric:"MTD4036"},
{name:"Paddock Dr. West at Winfield Village Lot G", ident:"PDKWLOTG", numeric:"MTD6466"},
{name:"Paddock Dr. West at Winfield Village Lot K", ident:"PDKWLOTK", numeric:"MTD6541"},
{name:"Paddock Dr. West at Winfield Village Lot M", ident:"PDKWLOTM", numeric:"MTD1156"},
{name:"Park <span class=\"amp\">&amp;</span> Mathews", ident:"PKMAT", numeric:"MTD2222"},
{name:"Park <span class=\"amp\">&amp;</span> Romine", ident:"PKRMN", numeric:"MTD1531"},
{name:"Park <span class=\"amp\">&amp;</span> Wright", ident:"PKWRT", numeric:"MTD4255"},
{name:"Parkland College", ident:"PKLN", numeric:"MTD3534"},
{name:"Parkland Ct. <span class=\"amp\">&amp;</span> Bradley", ident:"PKLNCTBRAD", numeric:"MTD0217"},
{name:"Paula <span class=\"amp\">&amp;</span> Mattis", ident:"PLAMATS", numeric:"MTD1553"},
{name:"Peabody at Krannert Art Museum", ident:"PDYKAM", numeric:"MTD5651"},
{name:"Pennsylvania <span class=\"amp\">&amp;</span> Anderson", ident:"PAADRSN", numeric:"MTD1143"},
{name:"Pennsylvania <span class=\"amp\">&amp;</span> Broadway", ident:"PABDWY", numeric:"MTD2733"},
{name:"Pennsylvania <span class=\"amp\">&amp;</span> Busey", ident:"PABUSEY", numeric:"MTD4673"},
{name:"Pennsylvania <span class=\"amp\">&amp;</span> Dorner", ident:"PADNR", numeric:"MTD0226"},
{name:"Pennsylvania <span class=\"amp\">&amp;</span> Fourth", ident:"PA4TH", numeric:"MTD3326"},
{name:"Pennsylvania <span class=\"amp\">&amp;</span> Goodwin", ident:"PAGWN", numeric:"MTD7174"},
{name:"Pennsylvania <span class=\"amp\">&amp;</span> Maryland Dr.", ident:"PAMD", numeric:"MTD2206"},
{name:"Pennsylvania <span class=\"amp\">&amp;</span> Orchard", ident:"PAORCH", numeric:"MTD3457"},
{name:"Pennsylvania <span class=\"amp\">&amp;</span> Sixth", ident:"PA6TH", numeric:"MTD2460"},
{name:"Pennsylvania <span class=\"amp\">&amp;</span> Vine", ident:"PAVIN", numeric:"MTD5474"},
{name:"Pennsylvania at PAR", ident:"PAPAR", numeric:"MTD0735"},
{name:"Philo <span class=\"amp\">&amp;</span> Michigan", ident:"PHILOMI", numeric:"MTD1026"},
{name:"Pinecrest <span class=\"amp\">&amp;</span> Staley", ident:"PNCRSTSTLY", numeric:"MTD6437"},
{name:"Plant Sciences Lab", ident:"PSL", numeric:"MTD6731"},
{name:"Prospect <span class=\"amp\">&amp;</span> Arbours Dr.", ident:"PSPCTARBR", numeric:"MTD3415"},
{name:"Prospect <span class=\"amp\">&amp;</span> Ayrshire Cir.", ident:"PSPCTASRC", numeric:"MTD4215"},
{name:"Prospect <span class=\"amp\">&amp;</span> Ayrshire Dr.", ident:"PSPCTASRD", numeric:"MTD0311"},
{name:"Prospect <span class=\"amp\">&amp;</span> Baytown", ident:"PSPCTBAY", numeric:"MTD6515"},
{name:"Prospect <span class=\"amp\">&amp;</span> Beardsley", ident:"PSPCTBRD", numeric:"MTD0626"},
{name:"Prospect <span class=\"amp\">&amp;</span> Bloomfield Ct.", ident:"PSPCTBLMCT", numeric:"MTD3247"},
{name:"Prospect <span class=\"amp\">&amp;</span> Broadmoor", ident:"PSPCTBDMR", numeric:"MTD3103"},
{name:"Prospect <span class=\"amp\">&amp;</span> Burwash", ident:"PSPCTBRWS", numeric:"MTD3106"},
{name:"Prospect <span class=\"amp\">&amp;</span> Columbia", ident:"PSPCTCLMBA", numeric:"MTD1414"},
{name:"Prospect <span class=\"amp\">&amp;</span> Dennison", ident:"PSPCTDNSN", numeric:"MTD1631"},
{name:"Prospect <span class=\"amp\">&amp;</span> Devonshire", ident:"PSPCTDVN", numeric:"MTD3260"},
{name:"Prospect <span class=\"amp\">&amp;</span> Eureka", ident:"PSPCTERKA", numeric:"MTD7253"},
{name:"Prospect <span class=\"amp\">&amp;</span> Floral Park", ident:"PSPCTFLRPK", numeric:"MTD2255"},
{name:"Prospect <span class=\"amp\">&amp;</span> Francis", ident:"PSPCTFRAN", numeric:"MTD3126"},
{name:"Prospect <span class=\"amp\">&amp;</span> Galen", ident:"PSPCTGALN", numeric:"MTD4006"},
{name:"Prospect <span class=\"amp\">&amp;</span> Harvard", ident:"PSPCTHVD", numeric:"MTD1011"},
{name:"Prospect <span class=\"amp\">&amp;</span> Hill", ident:"PSPCTHILL", numeric:"MTD7422"},
{name:"Prospect <span class=\"amp\">&amp;</span> Interstate", ident:"PSPCTINTER", numeric:"MTD5150"},
{name:"Prospect <span class=\"amp\">&amp;</span> Kent", ident:"PSPCTKENT", numeric:"MTD6063"},
{name:"Prospect <span class=\"amp\">&amp;</span> Kirby", ident:"PSPCTKBY", numeric:"MTD5725"},
{name:"Prospect <span class=\"amp\">&amp;</span> Lincolnshire", ident:"PSPCTLNSH", numeric:"MTD3261"},
{name:"Prospect <span class=\"amp\">&amp;</span> Maple", ident:"PSPCTMPL", numeric:"MTD5753"},
{name:"Prospect <span class=\"amp\">&amp;</span> Marketview", ident:"PSPCTMKTV", numeric:"MTD0407"},
{name:"Prospect <span class=\"amp\">&amp;</span> Park Lane", ident:"PSPCTPKLN", numeric:"MTD1134"},
{name:"Prospect <span class=\"amp\">&amp;</span> Pioneer", ident:"PSPCTPNR", numeric:"MTD5627"},
{name:"Prospect <span class=\"amp\">&amp;</span> Sherwood Terrace", ident:"PSPCTSHWD", numeric:"MTD6633"},
{name:"Prospect <span class=\"amp\">&amp;</span> Tremont", ident:"PSPCTTRMNT", numeric:"MTD7141"},
{name:"Prospect <span class=\"amp\">&amp;</span> Ventura", ident:"PSPCTVTRA", numeric:"MTD1150"},
{name:"Prospect <span class=\"amp\">&amp;</span> Vine", ident:"PSPCTVIN", numeric:"MTD4613"},
{name:"Prospect <span class=\"amp\">&amp;</span> Washington", ident:"PSPCTWASH", numeric:"MTD1325"},
{name:"Prospect at Lowes", ident:"PSPCTLOW", numeric:"MTD1025"},
{name:"Prospect at Meijer's Ent.", ident:"PSPCTMJR", numeric:"MTD4652"},
{name:"Race <span class=\"amp\">&amp;</span> California", ident:"RACECA", numeric:"MTD4263"},
{name:"Race <span class=\"amp\">&amp;</span> Green", ident:"RACEGRN", numeric:"MTD7255"},
{name:"Race <span class=\"amp\">&amp;</span> Illinois", ident:"RACEIL", numeric:"MTD5412"},
{name:"Race <span class=\"amp\">&amp;</span> Indiana", ident:"RACEIN", numeric:"MTD6103"},
{name:"Race <span class=\"amp\">&amp;</span> Main", ident:"RACEMN", numeric:"MTD4530"},
{name:"Race <span class=\"amp\">&amp;</span> Michigan", ident:"PACEMI", numeric:"MTD2172"},
{name:"Race <span class=\"amp\">&amp;</span> Michigan", ident:"RACEMI", numeric:"MTD2061"},
{name:"Race <span class=\"amp\">&amp;</span> Nevada", ident:"RACENV", numeric:"MTD4222"},
{name:"Race <span class=\"amp\">&amp;</span> Oregon", ident:"RACEOR", numeric:"MTD5012"},
{name:"Race at Meadowbrook Park", ident:"RACEMBRK", numeric:"MTD4243"},
{name:"Randolph <span class=\"amp\">&amp;</span> Maple", ident:"RNDLFMPL", numeric:"MTD2356"},
{name:"Randolph <span class=\"amp\">&amp;</span> Springfield", ident:"RNDLFSPFLD", numeric:"MTD1222"},
{name:"Randolph <span class=\"amp\">&amp;</span> University", ident:"RNDLFUNI", numeric:"MTD3447"},
{name:"Randolph <span class=\"amp\">&amp;</span> Vine", ident:"RNDLFVIN", numeric:"MTD7567"},
{name:"Romine <span class=\"amp\">&amp;</span> Beardsley", ident:"RMNBRD", numeric:"MTD2512"},
{name:"Romine <span class=\"amp\">&amp;</span> Bradley", ident:"RMNBRAD", numeric:"MTD0511"},
{name:"Romine <span class=\"amp\">&amp;</span> Eads", ident:"RMNEADS", numeric:"MTD6362"},
{name:"Romine <span class=\"amp\">&amp;</span> Ellis", ident:"RMNELLIS", numeric:"MTD5601"},
{name:"Romine <span class=\"amp\">&amp;</span> Eureka", ident:"RMNERKA", numeric:"MTD4040"},
{name:"Romine <span class=\"amp\">&amp;</span> Tremont", ident:"RMNTRMNT", numeric:"MTD4747"},
{name:"Savoy Walmart", ident:"SWALMART", numeric:"MTD5430"},
{name:"Scottswood <span class=\"amp\">&amp;</span> Illinois", ident:"SCWDIL", numeric:"MTD6465"},
{name:"Scottswood <span class=\"amp\">&amp;</span> Nevada", ident:"SCWDNV", numeric:"MTD0554"},
{name:"Scottswood <span class=\"amp\">&amp;</span> Oregon", ident:"SCWDOR", numeric:"MTD3721"},
{name:"Second <span class=\"amp\">&amp;</span> Church", ident:"2NDCHCH", numeric:"MTD6161"},
{name:"Second <span class=\"amp\">&amp;</span> Daniel", ident:"2NDDAN", numeric:"MTD4312"},
{name:"Second <span class=\"amp\">&amp;</span> Hill", ident:"2NDHILL", numeric:"MTD1777"},
{name:"Second <span class=\"amp\">&amp;</span> Park", ident:"2NDPK", numeric:"MTD2735"},
{name:"Second <span class=\"amp\">&amp;</span> University", ident:"2NDUNI", numeric:"MTD5743"},
{name:"Silver <span class=\"amp\">&amp;</span> Cottage Grove", ident:"SLVRCTGRV", numeric:"MTD6143"},
{name:"Sixth <span class=\"amp\">&amp;</span> Armory", ident:"6THARY", numeric:"MTD2214"},
{name:"Sixth <span class=\"amp\">&amp;</span> Bradley", ident:"6THBRAD", numeric:"MTD5422"},
{name:"Sixth <span class=\"amp\">&amp;</span> Chalmers", ident:"6THCHAL", numeric:"MTD1546"},
{name:"Sixth <span class=\"amp\">&amp;</span> Gregory", ident:"6THGRG", numeric:"MTD1523"},
{name:"Sixth <span class=\"amp\">&amp;</span> Peabody", ident:"6THPDY", numeric:"MTD0153"},
{name:"Sixth <span class=\"amp\">&amp;</span> Springfield", ident:"6THSPFLD", numeric:"MTD5324"},
{name:"Sixth <span class=\"amp\">&amp;</span> Stoughton", ident:"6THSTOTN", numeric:"MTD7643"},
{name:"Sixth <span class=\"amp\">&amp;</span> Taft", ident:"6THTFT", numeric:"MTD3344"},
{name:"South First St. Apts", ident:"S1ST", numeric:"MTD0441"},
{name:"Springer <span class=\"amp\">&amp;</span> Parkland Ct.", ident:"SGRPKLNCT", numeric:"MTD1034"},
{name:"Springfield <span class=\"amp\">&amp;</span> Birch", ident:"SPFLDBRCH", numeric:"MTD7732"},
{name:"Springfield <span class=\"amp\">&amp;</span> Busey", ident:"SPFLDBSY", numeric:"MTD6614"},
{name:"Springfield <span class=\"amp\">&amp;</span> Cedar", ident:"SPFLDCDR", numeric:"MTD6210"},
{name:"Springfield <span class=\"amp\">&amp;</span> Chicago", ident:"SPFLDCHI", numeric:"MTD6023"},
{name:"Springfield <span class=\"amp\">&amp;</span> Coler", ident:"SPFLDCLR", numeric:"MTD6436"},
{name:"Springfield <span class=\"amp\">&amp;</span> Cottage Ct.", ident:"SPFLDCTGCT", numeric:"MTD5026"},
{name:"Springfield <span class=\"amp\">&amp;</span> Country Fair Dr.", ident:"CFDSPFLD", numeric:"MTD4641"},
{name:"Springfield <span class=\"amp\">&amp;</span> Country Fair Dr.", ident:"SPFLDCFD", numeric:"MTD7311"},
{name:"Springfield <span class=\"amp\">&amp;</span> Country Fair", ident:"SPFLD", numeric:"MTD3162"},
{name:"Springfield <span class=\"amp\">&amp;</span> Draper", ident:"SPFLDDRPR", numeric:"MTD3202"},
{name:"Springfield <span class=\"amp\">&amp;</span> Duncan", ident:"SPFLDDNCN", numeric:"MTD6353"},
{name:"Springfield <span class=\"amp\">&amp;</span> Edwin", ident:"SPFLDEDWN", numeric:"MTD1217"},
{name:"Springfield <span class=\"amp\">&amp;</span> Elm", ident:"SPFLDELM", numeric:"MTD3762"},
{name:"Springfield <span class=\"amp\">&amp;</span> Elmwood", ident:"SPFLDEMWD", numeric:"MTD2431"},
{name:"Springfield <span class=\"amp\">&amp;</span> Fair", ident:"SPFLDFAIR", numeric:"MTD5142"},
{name:"Springfield <span class=\"amp\">&amp;</span> Flora", ident:"SPFLDFLRA", numeric:"MTD3566"},
{name:"Springfield <span class=\"amp\">&amp;</span> Garfield", ident:"SPFLDGRFLD", numeric:"MTD4037"},
{name:"Springfield <span class=\"amp\">&amp;</span> Gregory St.", ident:"SPFLDGRGST", numeric:"MTD5572"},
{name:"Springfield <span class=\"amp\">&amp;</span> Harvey", ident:"SPFLDHVY", numeric:"MTD4013"},
{name:"Springfield <span class=\"amp\">&amp;</span> Highland", ident:"SPFLDHILND", numeric:"MTD1554"},
{name:"Springfield <span class=\"amp\">&amp;</span> James", ident:"SPFLDJAS", numeric:"MTD4330"},
{name:"Springfield <span class=\"amp\">&amp;</span> Kelly Ct.", ident:"SPFLDKLYCT", numeric:"MTD4553"},
{name:"Springfield <span class=\"amp\">&amp;</span> Kenwood", ident:"SPFLDKNWD", numeric:"MTD5164"},
{name:"Springfield <span class=\"amp\">&amp;</span> Lincoln", ident:"SPFLDLNCLN", numeric:"MTD5352"},
{name:"Springfield <span class=\"amp\">&amp;</span> Lynn", ident:"SPFLDLYN", numeric:"MTD2660"},
{name:"Springfield <span class=\"amp\">&amp;</span> Mathews", ident:"SPFLDMAT", numeric:"MTD3526"},
{name:"Springfield <span class=\"amp\">&amp;</span> Mattis", ident:"SPFLDMATS", numeric:"MTD6135"},
{name:"Springfield <span class=\"amp\">&amp;</span> McCullough", ident:"SPFLDMCLGH", numeric:"MTD2454"},
{name:"Springfield <span class=\"amp\">&amp;</span> McKinley", ident:"SPFLDMCNLY", numeric:"MTD3446"},
{name:"Springfield <span class=\"amp\">&amp;</span> New", ident:"SPFLDNEW", numeric:"MTD4740"},
{name:"Springfield <span class=\"amp\">&amp;</span> Pine", ident:"SPFLDPINE", numeric:"MTD4347"},
{name:"Springfield <span class=\"amp\">&amp;</span> Prairie", ident:"SPFLDPRRE", numeric:"MTD4432"},
{name:"Springfield <span class=\"amp\">&amp;</span> Prospect", ident:"SPFLDPSPCT", numeric:"MTD1746"},
{name:"Springfield <span class=\"amp\">&amp;</span> Ridgeway", ident:"SPFLDRGWY", numeric:"MTD5220"},
{name:"Springfield <span class=\"amp\">&amp;</span> Royal Ct.", ident:"SPFLDRYLCT", numeric:"MTD6531"},
{name:"Springfield <span class=\"amp\">&amp;</span> Russell", ident:"SPFLDRSL", numeric:"MTD5647"},
{name:"Springfield <span class=\"amp\">&amp;</span> Southwest Country Fair", ident:"SWCF", numeric:"MTD7665"},
{name:"Springfield <span class=\"amp\">&amp;</span> VanDoren", ident:"SPFLDVNDRN", numeric:"MTD6134"},
{name:"Springfield <span class=\"amp\">&amp;</span> Westlawn", ident:"SPFLDWLWN", numeric:"MTD2421"},
{name:"Springfield <span class=\"amp\">&amp;</span> Wheaton", ident:"SPFLDWHTN", numeric:"MTD0414"},
{name:"Springfield <span class=\"amp\">&amp;</span> Willis", ident:"SPFLDWLS", numeric:"MTD3315"},
{name:"Springfield at Armed Forces Recruiting", ident:"SPFLDAFRC", numeric:"MTD6412"},
{name:"St Mary's Road <span class=\"amp\">&amp;</span> Neil", ident:"SMRNEIL", numeric:"MTD2103"},
{name:"St. Mary's <span class=\"amp\">&amp;</span> First", ident:"SMR1ST", numeric:"MTD0625"},
{name:"St. Mary's Road <span class=\"amp\">&amp;</span> Oak", ident:"SMROAK", numeric:"MTD6654"},
{name:"St. Mathews Parking Lot <span class=\"amp\">&amp;</span> Lincolnshire Dr.", ident:"LCNSR", numeric:"MTD7445"},
{name:"St. Mathews", ident:"STMAT", numeric:"MTD2444"},
{name:"Stadium <span class=\"amp\">&amp;</span> Oak", ident:"STDMOAK", numeric:"MTD4373"},
{name:"Staley <span class=\"amp\">&amp;</span> Amherst", ident:"STLYAMHT", numeric:"MTD2012"},
{name:"Staley <span class=\"amp\">&amp;</span> Kirby", ident:"STLYKBY", numeric:"MTD0427"},
{name:"Staley <span class=\"amp\">&amp;</span> Turnberry", ident:"STLYTRNBRY", numeric:"MTD2422"},
{name:"State <span class=\"amp\">&amp;</span> Avondale", ident:"STEAVNDL", numeric:"MTD6062"},
{name:"State <span class=\"amp\">&amp;</span> Beardsley", ident:"STEBRD", numeric:"MTD0235"},
{name:"State <span class=\"amp\">&amp;</span> Birch", ident:"STEBRCH", numeric:"MTD0523"},
{name:"State <span class=\"amp\">&amp;</span> Buena Vista", ident:"STEBV", numeric:"MTD5210"},
{name:"State <span class=\"amp\">&amp;</span> Cedar", ident:"STECDR", numeric:"MTD6121"},
{name:"State <span class=\"amp\">&amp;</span> Charles", ident:"STECHAS", numeric:"MTD4130"},
{name:"State <span class=\"amp\">&amp;</span> Clark", ident:"STECLARK", numeric:"MTD3153"},
{name:"State <span class=\"amp\">&amp;</span> Columbia", ident:"STECLMBA", numeric:"MTD2754"},
{name:"State <span class=\"amp\">&amp;</span> Ells", ident:"STEELS", numeric:"MTD3304"},
{name:"State <span class=\"amp\">&amp;</span> Eureka", ident:"STEERKA", numeric:"MTD2423"},
{name:"State <span class=\"amp\">&amp;</span> Healey", ident:"STEHLY", numeric:"MTD6467"},
{name:"State <span class=\"amp\">&amp;</span> Hessel Blvd.", ident:"STEHSL", numeric:"MTD5034"},
{name:"State <span class=\"amp\">&amp;</span> Hill", ident:"STEHIL", numeric:"MTD4150"},
{name:"State <span class=\"amp\">&amp;</span> John", ident:"STEJOHN", numeric:"MTD1661"},
{name:"State <span class=\"amp\">&amp;</span> Maple", ident:"STEMPL", numeric:"MTD6363"},
{name:"State <span class=\"amp\">&amp;</span> Park", ident:"STEPK", numeric:"MTD0074"},
{name:"State <span class=\"amp\">&amp;</span> Springfield", ident:"STESPFLD", numeric:"MTD2746"},
{name:"State <span class=\"amp\">&amp;</span> Stanage", ident:"STESTNAG", numeric:"MTD1714"},
{name:"State <span class=\"amp\">&amp;</span> Trade Center Dr.", ident:"STETC", numeric:"MTD3710"},
{name:"State <span class=\"amp\">&amp;</span> Tremont", ident:"STETRMNT", numeric:"MTD6320"},
{name:"State <span class=\"amp\">&amp;</span> University", ident:"STEUNI", numeric:"MTD2450"},
{name:"State <span class=\"amp\">&amp;</span> Vine", ident:"STEVIN", numeric:"MTD2315"},
{name:"State <span class=\"amp\">&amp;</span> Washington", ident:"STEWASH", numeric:"MTD3501"},
{name:"State <span class=\"amp\">&amp;</span> White", ident:"STEWHT", numeric:"MTD1404"},
{name:"State <span class=\"amp\">&amp;</span> William", ident:"STEWLM", numeric:"MTD4525"},
{name:"Sunnycrest Mall", ident:"FLSUN", numeric:"MTD5325"},
{name:"Sunnycrest Shopping Center", ident:"SUNNYCREST", numeric:"MTD6464"},
{name:"Third <span class=\"amp\">&amp;</span> Daniel", ident:"3RDDAN", numeric:"MTD4505"},
{name:"Town Center <span class=\"amp\">&amp;</span> Meijer", ident:"TCBMJR", numeric:"MTD2015"},
{name:"Town Center <span class=\"amp\">&amp;</span> Prospect", ident:"TCBPSPCT", numeric:"MTD4615"},
{name:"Town Center Blvd <span class=\"amp\">&amp;</span> Neil", ident:"TCBNEIL", numeric:"MTD3562"},
{name:"Transit Plaza (Eastside)", ident:"PLAZA", numeric:"MTD6115"},
{name:"Transit Plaza (Westside)", ident:"PLAZA", numeric:"MTD5404"},
{name:"Transit Plaza", ident:"PLAZA", numeric:"MTD7411"},
{name:"U of I Credit Union - First <span class=\"amp\">&amp;</span> Gerty", ident:"UICU", numeric:"MTD5616"},
{name:"U.S. 150 <span class=\"amp\">&amp;</span> University", ident:"150UNI", numeric:"MTD6741"},
{name:"University <span class=\"amp\">&amp;</span> Ambucs Park Entrance", ident:"AMBUC", numeric:"MTD4322"},
{name:"University <span class=\"amp\">&amp;</span> Ash", ident:"UNIASH", numeric:"MTD1476"},
{name:"University <span class=\"amp\">&amp;</span> Busey", ident:"UNIBUSEY", numeric:"MTD2020"},
{name:"University <span class=\"amp\">&amp;</span> Central", ident:"UNICENT", numeric:"MTD4025"},
{name:"University <span class=\"amp\">&amp;</span> Chester", ident:"UNICHSTR", numeric:"MTD1425"},
{name:"University <span class=\"amp\">&amp;</span> Chestnut", ident:"UNICHSNT", numeric:"MTD4470"},
{name:"University <span class=\"amp\">&amp;</span> Coler", ident:"UNICLR", numeric:"MTD7441"},
{name:"University <span class=\"amp\">&amp;</span> Cottage Grove", ident:"UNICTGRV", numeric:"MTD5343"},
{name:"University <span class=\"amp\">&amp;</span> Draper", ident:"UNIDRPR", numeric:"MTD6235"},
{name:"University <span class=\"amp\">&amp;</span> Elm", ident:"UNIELM", numeric:"MTD0452"},
{name:"University <span class=\"amp\">&amp;</span> Fair", ident:"UNIFAIR", numeric:"MTD3062"},
{name:"University <span class=\"amp\">&amp;</span> Fifth", ident:"UNI5TH", numeric:"MTD1016"},
{name:"University <span class=\"amp\">&amp;</span> First", ident:"UNI1ST", numeric:"MTD5251"},
{name:"University <span class=\"amp\">&amp;</span> Fourth", ident:"UNI4TH", numeric:"MTD3521"},
{name:"University <span class=\"amp\">&amp;</span> Goodwin", ident:"UNIGWN", numeric:"MTD1327"},
{name:"University <span class=\"amp\">&amp;</span> Gregory St.", ident:"UNIGRGST", numeric:"MTD5263"},
{name:"University <span class=\"amp\">&amp;</span> Harvey", ident:"UNIHVY", numeric:"MTD1124"},
{name:"University <span class=\"amp\">&amp;</span> Hickory", ident:"UNIHKRY", numeric:"MTD5303"},
{name:"University <span class=\"amp\">&amp;</span> James", ident:"UNIJAS", numeric:"MTD4340"},
{name:"University <span class=\"amp\">&amp;</span> Lake", ident:"UNILAKE", numeric:"MTD7243"},
{name:"University <span class=\"amp\">&amp;</span> Lierman", ident:"UNILRMN", numeric:"MTD6626"},
{name:"University <span class=\"amp\">&amp;</span> Lincoln", ident:"UNILNCLN", numeric:"MTD3635"},
{name:"University <span class=\"amp\">&amp;</span> Lynn", ident:"UNILYN", numeric:"MTD3653"},
{name:"University <span class=\"amp\">&amp;</span> Maple", ident:"UNIMPL", numeric:"MTD1266"},
{name:"University <span class=\"amp\">&amp;</span> Market", ident:"UNIMKT", numeric:"MTD1323"},
{name:"University <span class=\"amp\">&amp;</span> Mattis", ident:"UNIMATS", numeric:"MTD0662"},
{name:"University <span class=\"amp\">&amp;</span> McCullough", ident:"UNIMCLGH", numeric:"MTD4066"},
{name:"University <span class=\"amp\">&amp;</span> McKinley", ident:"UNIMCNLY", numeric:"MTD2221"},
{name:"University <span class=\"amp\">&amp;</span> Neil", ident:"UNINEIL", numeric:"MTD5450"},
{name:"University <span class=\"amp\">&amp;</span> New", ident:"UNINEW", numeric:"MTD4606"},
{name:"University <span class=\"amp\">&amp;</span> Orchard", ident:"UNIOD", numeric:"MTD3363"},
{name:"University <span class=\"amp\">&amp;</span> Prairie", ident:"UNIPRRE", numeric:"MTD1350"},
{name:"University <span class=\"amp\">&amp;</span> Prospect", ident:"UNIPSPCT", numeric:"MTD1221"},
{name:"University <span class=\"amp\">&amp;</span> Race", ident:"UNIRACE", numeric:"MTD2715"},
{name:"University <span class=\"amp\">&amp;</span> Randolph", ident:"UNIRNDLF", numeric:"MTD6262"},
{name:"University <span class=\"amp\">&amp;</span> Russell", ident:"UNIRSL", numeric:"MTD3242"},
{name:"University <span class=\"amp\">&amp;</span> Sabin", ident:"UNISBN", numeric:"MTD6434"},
{name:"University <span class=\"amp\">&amp;</span> Second", ident:"UNI2ND", numeric:"MTD4210"},
{name:"University <span class=\"amp\">&amp;</span> Sixth", ident:"UNI6TH", numeric:"MTD5377"},
{name:"University <span class=\"amp\">&amp;</span> State", ident:"UNISTE", numeric:"MTD4257"},
{name:"University <span class=\"amp\">&amp;</span> Sycamore", ident:"UNISCMR", numeric:"MTD3001"},
{name:"University <span class=\"amp\">&amp;</span> Third", ident:"UNI3RD", numeric:"MTD3555"},
{name:"University <span class=\"amp\">&amp;</span> Victor", ident:"UNIVCTR", numeric:"MTD6213"},
{name:"University <span class=\"amp\">&amp;</span> Vine", ident:"UNIVIN", numeric:"MTD3356"},
{name:"University <span class=\"amp\">&amp;</span> Walnut", ident:"UNIWLNT", numeric:"MTD4012"},
{name:"University <span class=\"amp\">&amp;</span> Willis", ident:"UNIWLS", numeric:"MTD5112"},
{name:"University <span class=\"amp\">&amp;</span> Wright", ident:"UNIWRT", numeric:"MTD6365"},
{name:"University at MTD", ident:"UNIMTD", numeric:"MTD4140"},
{name:"Urbana High School", ident:"UHS", numeric:"MTD2361"},
{name:"Urbana Lot 24", ident:"LOT24", numeric:"MTD1213"},
{name:"Urbana Meijer", ident:"URBMEIJ", numeric:"MTD5053"},
{name:"Urbana Middle School South Side", ident:"UMSS", numeric:"MTD4265"},
{name:"Urbana Middle School", ident:"UMS", numeric:"MTD4310"},
{name:"Urbana Walmart", ident:"UWALMART", numeric:"MTD0127"},
{name:"Vine <span class=\"amp\">&amp;</span> Brookens", ident:"VINBRKNS", numeric:"MTD0327"},
{name:"Vine <span class=\"amp\">&amp;</span> Burkwood Ct. W.", ident:"VINBKWD", numeric:"MTD6100"},
{name:"Vine <span class=\"amp\">&amp;</span> California", ident:"VINCA", numeric:"MTD0636"},
{name:"Vine <span class=\"amp\">&amp;</span> Colorado", ident:"VINCO", numeric:"MTD4757"},
{name:"Vine <span class=\"amp\">&amp;</span> Elm", ident:"VINELM", numeric:"MTD2270"},
{name:"Vine <span class=\"amp\">&amp;</span> Evergreen Ct. W", ident:"VINEGRN", numeric:"MTD2205"},
{name:"Vine <span class=\"amp\">&amp;</span> Fairlawn", ident:"VINFRLN", numeric:"MTD6167"},
{name:"Vine <span class=\"amp\">&amp;</span> George Huff", ident:"VINGHF", numeric:"MTD2325"},
{name:"Vine <span class=\"amp\">&amp;</span> Green", ident:"VINGRN", numeric:"MTD7423"},
{name:"Vine <span class=\"amp\">&amp;</span> Harris", ident:"VINHRIS", numeric:"MTD5553"},
{name:"Vine <span class=\"amp\">&amp;</span> Holmes", ident:"VINHLMS", numeric:"MTD3464"},
{name:"Vine <span class=\"amp\">&amp;</span> Illinois", ident:"VINIL", numeric:"MTD3100"},
{name:"Vine <span class=\"amp\">&amp;</span> Lynn", ident:"VINLYN", numeric:"MTD3703"},
{name:"Vine <span class=\"amp\">&amp;</span> Main", ident:"VINMN", numeric:"MTD4662"},
{name:"Vine <span class=\"amp\">&amp;</span> McHenry", ident:"VINMHRY", numeric:"MTD2245"},
{name:"Vine <span class=\"amp\">&amp;</span> McKinley", ident:"VINMCNLY", numeric:"MTD3621"},
{name:"Vine <span class=\"amp\">&amp;</span> Montclair", ident:"VINMNTCLR", numeric:"MTD3407"},
{name:"Vine <span class=\"amp\">&amp;</span> Mumford", ident:"VINMFRD", numeric:"MTD4043"},
{name:"Vine <span class=\"amp\">&amp;</span> Nevada", ident:"VINNV", numeric:"MTD5774"},
{name:"Vine <span class=\"amp\">&amp;</span> Oregon", ident:"VINOR", numeric:"MTD5151"},
{name:"Vine <span class=\"amp\">&amp;</span> Pell Cir.", ident:"VINPELL", numeric:"MTD6441"},
{name:"Vine <span class=\"amp\">&amp;</span> Prairie", ident:"VINPRRE", numeric:"MTD5434"},
{name:"Vine <span class=\"amp\">&amp;</span> Scovill", ident:"VINSCVL", numeric:"MTD6367"},
{name:"Vine <span class=\"amp\">&amp;</span> Shurts", ident:"VINSRTS", numeric:"MTD0336"},
{name:"Vine <span class=\"amp\">&amp;</span> Sunnycrest", ident:"VINSNYC", numeric:"MTD1643"},
{name:"Vine <span class=\"amp\">&amp;</span> Washington", ident:"VINWASH", numeric:"MTD1317"},
{name:"Vine <span class=\"amp\">&amp;</span> Water", ident:"VINWTR", numeric:"MTD3105"},
{name:"Vine <span class=\"amp\">&amp;</span> Wills", ident:"VINWLS", numeric:"MTD4120"},
{name:"Vine <span class=\"amp\">&amp;</span> Windsor", ident:"VINWDSR", numeric:"MTD1637"},
{name:"Virginia <span class=\"amp\">&amp;</span> College Ct.", ident:"VACC", numeric:"MTD6345"},
{name:"Walnut <span class=\"amp\">&amp;</span> Bailey", ident:"WLNTBLY", numeric:"MTD3462"},
{name:"Walnut <span class=\"amp\">&amp;</span> Columbia", ident:"WLNTCLMBA", numeric:"MTD4677"},
{name:"Walnut <span class=\"amp\">&amp;</span> Logan", ident:"WLNTLGN", numeric:"MTD4276"},
{name:"Walnut <span class=\"amp\">&amp;</span> Main", ident:"WLNTMN", numeric:"MTD2663"},
{name:"Walnut <span class=\"amp\">&amp;</span> Taylor", ident:"WLNTTYLR", numeric:"MTD5143"},
{name:"Walnut <span class=\"amp\">&amp;</span> University", ident:"WLNTUNI", numeric:"MTD2674"},
{name:"Walnut <span class=\"amp\">&amp;</span> Washington", ident:"WLNTWASH", numeric:"MTD6176"},
{name:"Washington <span class=\"amp\">&amp;</span> Anderson", ident:"WASHADRSN", numeric:"MTD3425"},
{name:"Washington <span class=\"amp\">&amp;</span> Fourth", ident:"WASH4TH", numeric:"MTD2062"},
{name:"Washington <span class=\"amp\">&amp;</span> Second", ident:"WASH2ND", numeric:"MTD2040"},
{name:"Washington <span class=\"amp\">&amp;</span> Third", ident:"WASH3RD", numeric:"MTD3337"},
{name:"Water Survey", ident:"ISWS", numeric:"MTD1216"},
{name:"Wedgewood <span class=\"amp\">&amp;</span> Duncan", ident:"WGWDDNCN", numeric:"MTD2670"},
{name:"Westfield <span class=\"amp\">&amp;</span> Alton", ident:"WSFLDALTN", numeric:"MTD6417"},
{name:"Westfield <span class=\"amp\">&amp;</span> Carrelton", ident:"WSFLDCRLTN", numeric:"MTD0573"},
{name:"Westfield <span class=\"amp\">&amp;</span> Lawndale", ident:"WSFLDLWNDL", numeric:"MTD6123"},
{name:"Westfield <span class=\"amp\">&amp;</span> Sangamon", ident:"WSFLDSANG", numeric:"MTD6055"},
{name:"Westfield <span class=\"amp\">&amp;</span> Sheridan", ident:"WSFLDSRDN", numeric:"MTD1725"},
{name:"Westfield <span class=\"amp\">&amp;</span> William", ident:"WSFLDWLM", numeric:"MTD7615"},
{name:"White <span class=\"amp\">&amp;</span> Fifth", ident:"WHT5TH", numeric:"MTD5605"},
{name:"White <span class=\"amp\">&amp;</span> First", ident:"WHT1ST", numeric:"MTD3364"},
{name:"White <span class=\"amp\">&amp;</span> Fourth", ident:"WHT4TH", numeric:"MTD2343"},
{name:"White <span class=\"amp\">&amp;</span> Second", ident:"WHT2ND", numeric:"MTD4655"},
{name:"White <span class=\"amp\">&amp;</span> Sixth", ident:"WHT6TH", numeric:"MTD6711"},
{name:"White <span class=\"amp\">&amp;</span> Third", ident:"WHT3RD", numeric:"MTD1755"},
{name:"White <span class=\"amp\">&amp;</span> Wright", ident:"WHTWRT", numeric:"MTD4551"},
{name:"Willard Airport", ident:"WILLARD", numeric:"MTD5405"},
{name:"William <span class=\"amp\">&amp;</span> Duncan", ident:"WLMDNCN", numeric:"MTD5402"},
{name:"William <span class=\"amp\">&amp;</span> Fair Oaks", ident:"WLMFROAK", numeric:"MTD4144"},
{name:"William <span class=\"amp\">&amp;</span> Kenwood", ident:"WLMKNWD", numeric:"MTD6234"},
{name:"Williamsburg <span class=\"amp\">&amp;</span> Mattis", ident:"WMBGMATS", numeric:"MTD1605"},
{name:"Windsor <span class=\"amp\">&amp;</span> Duncan", ident:"WDSRDNCN", numeric:"MTD2526"},
{name:"Windsor <span class=\"amp\">&amp;</span> Farmington", ident:"WDSRFMTN", numeric:"MTD0253"},
{name:"Windsor <span class=\"amp\">&amp;</span> Lincoln", ident:"WDSRLNCLN", numeric:"MTD7115"},
{name:"Windsor <span class=\"amp\">&amp;</span> Lynn", ident:"WDSRLYN", numeric:"MTD5531"},
{name:"Windsor <span class=\"amp\">&amp;</span> Morrissey Park Dr.", ident:"WDSRMYPK", numeric:"MTD7524"},
{name:"Windsor <span class=\"amp\">&amp;</span> Prospect", ident:"WDSRPSPCT", numeric:"MTD2641"},
{name:"Windsor <span class=\"amp\">&amp;</span> Staley", ident:"WNDSRSTLY", numeric:"MTD7416"},
{name:"Woodfield at Savoy 16 Theaters", ident:"WDFLDSV16", numeric:"MTD3453"},
{name:"Woodfield at Savoy 16", ident:"WDLFDSV16", numeric:"MTD1654"},
{name:"Wright <span class=\"amp\">&amp;</span> Beech", ident:"WRTBCH", numeric:"MTD3330"},
{name:"Wright <span class=\"amp\">&amp;</span> Beslin", ident:"WRTBSLN", numeric:"MTD5222"},
{name:"Wright <span class=\"amp\">&amp;</span> Chalmers", ident:"WRTCHAL", numeric:"MTD4164"},
{name:"Wright <span class=\"amp\">&amp;</span> Church", ident:"WRTCHCH", numeric:"MTD2761"},
{name:"Wright <span class=\"amp\">&amp;</span> Clark", ident:"WRTCLARK", numeric:"MTD6356"},
{name:"Wright <span class=\"amp\">&amp;</span> Columbia", ident:"WRTCLMBA", numeric:"MTD2373"},
{name:"Wright <span class=\"amp\">&amp;</span> Dublin", ident:"WRTDBLN", numeric:"MTD2375"},
{name:"Wright <span class=\"amp\">&amp;</span> Healey", ident:"WRTHLY", numeric:"MTD5532"},
{name:"Wright <span class=\"amp\">&amp;</span> Hill", ident:"WRTHIL", numeric:"MTD4463"},
{name:"Wright <span class=\"amp\">&amp;</span> Springfield", ident:"WRTSPFLD", numeric:"MTD3766"},
{name:"Wright <span class=\"amp\">&amp;</span> Stoughton", ident:"WRTSTOTN", numeric:"MTD6544"},
{name:"Wright <span class=\"amp\">&amp;</span> Washington", ident:"WRTWASH", numeric:"MTD4051"}, ]
